<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pendaftaran</name>
   <tag></tag>
   <elementGuidId>4e6bf920-6845-41c0-a5a7-671de974520b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>961e4f32-125d-4826-98ec-f9a817a5518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pendaftaran/create/0000000001016964</value>
      <webElementGuid>2b9f4789-5ca8-4a30-9b7d-3f7840537462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_next</value>
      <webElementGuid>508372b1-7a46-4472-aef0-999e3cdc906b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>b9e70d8b-89a0-48e2-983a-beb9a7dc2c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendaftaran</value>
      <webElementGuid>36d0527a-9089-44c9-8645-67484d778e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_next&quot;)</value>
      <webElementGuid>39f99d03-46d6-4f8d-97de-7dc8e80adaba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_next']</value>
      <webElementGuid>2d7cd85a-d53f-4937-b2c7-3cd336b7e333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/span[2]/a[5]</value>
      <webElementGuid>e77f9b84-10a9-4104-a92b-a1950b69b707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pendaftaran')])[4]</value>
      <webElementGuid>e3d9345e-9b81-46af-bebf-5f99ac766722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[1]/following::a[1]</value>
      <webElementGuid>98b81daf-9003-44ca-b02a-68a105295e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::a[2]</value>
      <webElementGuid>8974b5d6-c565-40af-b108-eacaa92cfbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran Laboratorium'])[1]/preceding::a[1]</value>
      <webElementGuid>174c13a9-357e-458b-b55d-250aaa858a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penimbangan Balita'])[2]/preceding::a[2]</value>
      <webElementGuid>86df6999-4548-482b-9c67-3c14b8557564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pendaftaran/create/0000000001016964')]</value>
      <webElementGuid>d0afe64d-3b44-4569-9452-f4dfb98bdce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>817c1a25-bcac-400e-a736-344d1fcea426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.epuskesmas.id/pendaftaran/create/0000000001016964' and @id = 'button_next' and (text() = 'Pendaftaran' or . = 'Pendaftaran')]</value>
      <webElementGuid>00abc6cd-dca8-4e93-bbc5-4f0d5f76ab8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
