<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Willem PUSKESMAS PUSKESMAS1</name>
   <tag></tag>
   <elementGuidId>da6114d6-c496-44f3-b76b-d65fc8791d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_user']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1994b060-80a8-4b66-897a-5330fbc647b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_user</value>
      <webElementGuid>7e1e97db-0274-4695-bebd-227d25f8c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>38df4ac5-3c87-4e92-931e-30f452e3d303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>13e31b13-4b16-42ee-a5da-17dc11aa8264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>cb308ac9-ab0d-45a1-a8a0-9ed1e5461e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c73f5ace-46b7-4a4b-b4da-2fc86989e9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e13ff82-63a8-45b5-9c5f-d86f0b409c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Willem PUSKESMAS PUSKESMAS1 
                                </value>
      <webElementGuid>0f6b44f5-f3ae-458c-809f-6511927c1a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_user&quot;)</value>
      <webElementGuid>1d6c0bfe-fe28-443e-a8a2-36d24055bc22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_user']</value>
      <webElementGuid>c7542048-3ca1-4992-ad39-796d28ff6c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul[2]/li[3]/a</value>
      <webElementGuid>5c6994cc-40eb-4b21-a6f0-0811a2d21ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Bridging'])[1]/following::a[1]</value>
      <webElementGuid>58fbb4f9-019a-43b9-9297-efdb10c4dc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Tahunan LSD 3'])[1]/following::a[3]</value>
      <webElementGuid>e8cfe081-1724-4f1a-9881-65f6826d92c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/preceding::a[1]</value>
      <webElementGuid>d5d87bcf-b3ed-43dc-bd1b-44bc0313112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Willem']/parent::*</value>
      <webElementGuid>5694d6ee-d29c-4a87-97ad-9ef23cda792b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>9c271e7c-22c6-4738-88af-69f84a4d70c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>49d57289-4cdd-4db8-bf1e-827538bd12eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_user' and @href = '#' and (text() = '
                                    Willem PUSKESMAS PUSKESMAS1 
                                ' or . = '
                                    Willem PUSKESMAS PUSKESMAS1 
                                ')]</value>
      <webElementGuid>9867bd28-1545-4b70-afea-0b1bbe62551c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
