<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medis</name>
   <tag></tag>
   <elementGuidId>87903b8e-10b9-458a-a6d5-51ecf5937000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pelayanan_medis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_pelayanan_medis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e16cc7d-2f04-4144-b8eb-6f870b2d735e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pelayanan_medis</value>
      <webElementGuid>b3970fc0-2b2b-423b-b14a-594e5173d079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pelayanan?broadcastNotif=1</value>
      <webElementGuid>5aedcf13-8355-4966-8a83-583e7b2575b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medis</value>
      <webElementGuid>e77ecee9-647d-45e9-bb98-d8b9c3052091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pelayanan_medis&quot;)</value>
      <webElementGuid>fe8368af-14a2-40bb-821c-f767993ab20c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pelayanan_medis']</value>
      <webElementGuid>e0c66a16-6d26-47c7-a053-8f245bd6c826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>970f0f49-ef8a-447c-b0be-846377ae63f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Medis')])[2]</value>
      <webElementGuid>04b78f67-6e6c-43b6-8608-c7149a5a551a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelayanan'])[2]/following::a[1]</value>
      <webElementGuid>1b0f4064-b5be-432e-b295-aee8118b4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panggil Antrean'])[1]/following::a[2]</value>
      <webElementGuid>fa3432a5-61e3-4411-8171-6040aadef5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[1]/preceding::a[1]</value>
      <webElementGuid>dd6e5337-27a7-40af-bc8d-942b342eaa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obat Pasien'])[1]/preceding::a[2]</value>
      <webElementGuid>2ce52c3d-241c-48df-8e3a-02bce0f0e21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medis']/parent::*</value>
      <webElementGuid>c39cf61e-fe2a-497f-8791-fd8d489a44fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pelayanan?broadcastNotif=1')]</value>
      <webElementGuid>3ec6e831-830e-408c-82f7-d2b25cf29d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>9af60c33-ec40-4762-928f-2babe4674549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_pelayanan_medis' and @href = 'https://demo.epuskesmas.id/pelayanan?broadcastNotif=1' and (text() = 'Medis' or . = 'Medis')]</value>
      <webElementGuid>7845cdad-d689-4f81-b470-0ee840976f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
