<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Umum9100</name>
   <tag></tag>
   <elementGuidId>ff0adfde-23a7-4183-9715-24a05fa3596c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='ruangan_id_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ruangan_id_0001&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75afe2b8-4d1a-4b5b-8e45-b897f7f97b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fde8be8-7213-4435-8ef6-f00c7236c71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruangan_id_0001</value>
      <webElementGuid>5d716223-3344-452e-8149-d0e0b5aa0200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-list btn-info bpoli</value>
      <webElementGuid>ed278022-d707-45d0-8d6c-8a9e9a57ab75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setOptionKamar('0001')</value>
      <webElementGuid>d5f9f058-b6a3-415b-879c-484f2f412882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdpoli</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>dd19d3d8-2e91-4b4b-85c3-c81ec4117272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nmpoli</name>
      <type>Main</type>
      <value>POLI UMUM</value>
      <webElementGuid>dac9a1db-811d-48db-b338-cdad27dc1826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdruang</name>
      <type>Main</type>
      <value>0001</value>
      <webElementGuid>d00175da-86d5-467b-9845-9905bf9480c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Umum9/100</value>
      <webElementGuid>5148905c-15b0-463e-a1b5-c18f5eed9918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info bpoli&quot;]</value>
      <webElementGuid>32b577f0-8a09-4368-9763-bb94b931fcea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='ruangan_id_0001']</value>
      <webElementGuid>f269e7a7-3d59-4b8b-987f-ffa16c136967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button</value>
      <webElementGuid>e2b2fda6-4455-477a-9096-5d14b34ec639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::button[1]</value>
      <webElementGuid>9ac224c3-d9fa-40b4-8bf1-51795eed6751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/button</value>
      <webElementGuid>da3c1f98-4b1f-41c4-ad97-fb5b0f586691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'ruangan_id_0001' and (text() = '  Umum9/100' or . = '  Umum9/100')]</value>
      <webElementGuid>33996345-7886-4745-9c0d-6c00ed3eef6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
