<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rawat Jalan</name>
   <tag></tag>
   <elementGuidId>d7d87e9f-2c74-4894-a831-924094e38274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='instalasi_id_01']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;instalasi_id_01&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cdd0209-e3e4-41bf-9593-5c2c29e1aef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a603eb29-5613-473d-a1df-a3adeab3ff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instalasi_id_01</value>
      <webElementGuid>4e566617-7968-4d63-a2c5-d54fb24c885c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-list btn-info </value>
      <webElementGuid>1b37521d-7fac-41c3-82ab-03522d2c443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setOptionRuangan('01')</value>
      <webElementGuid>d1ba8c3e-6696-45c7-a233-1492de24f59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Rawat Jalan</value>
      <webElementGuid>57540f91-349b-49e0-849e-3f90f04955df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info&quot;]</value>
      <webElementGuid>195a53e3-f6a8-4cdb-85be-95fd02099f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='instalasi_id_01']</value>
      <webElementGuid>720eea01-60ff-4a8a-a9f0-c5b76e305385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div/div/span/div/button</value>
      <webElementGuid>1d8ae13b-c850-4824-8600-3c9af341c7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::button[1]</value>
      <webElementGuid>5872c35e-c2da-4cba-ad21-4df98327f9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gawat Darurat'])[1]/preceding::button[1]</value>
      <webElementGuid>a8388c9f-1da2-4a8c-a889-0d9d2d085908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rawat Inap'])[1]/preceding::button[2]</value>
      <webElementGuid>6cb95ffc-df28-4007-b17c-a71d36e7412e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rawat Jalan']/parent::*</value>
      <webElementGuid>e8cb03eb-e266-4453-a732-df86b081b50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button</value>
      <webElementGuid>1051c5d9-ffc7-4721-afc4-908eb10fb21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'instalasi_id_01' and (text() = ' Rawat Jalan' or . = ' Rawat Jalan')]</value>
      <webElementGuid>7f09896d-54ce-4de5-b5ef-f133d843325c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
