<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Umum3100</name>
   <tag></tag>
   <elementGuidId>312946b5-4356-42a0-979e-7df2f4ec4fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='ruangan_id_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ruangan_id_0001&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8bcda20-eaad-4a6b-80bf-f482ff3e9145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf123a04-7ea1-4d1e-b247-91e7868adaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruangan_id_0001</value>
      <webElementGuid>87446015-3785-4659-91d4-05d85ad86ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-list btn-info bpoli</value>
      <webElementGuid>e552aff5-ccfc-4366-bc53-510e40c1f796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setOptionKamar('0001')</value>
      <webElementGuid>1954f1d2-db67-4bde-bbba-25dc22ae0a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdpoli</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>6bb68058-26ac-4370-a44c-9685378e0607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nmpoli</name>
      <type>Main</type>
      <value>POLI UMUM</value>
      <webElementGuid>2e859295-b157-4a2a-82a6-63f2ef2e8ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdruang</name>
      <type>Main</type>
      <value>0001</value>
      <webElementGuid>b465f747-ae4a-46ad-b932-68ec31ea7c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Umum3/100</value>
      <webElementGuid>b7a4ca49-bd99-4961-aadd-537a2e906c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info bpoli&quot;]</value>
      <webElementGuid>6b48d506-e1c4-4608-8a21-f5273bd58cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='ruangan_id_0001']</value>
      <webElementGuid>edfbf0de-3a1e-4365-957c-04851a9ea4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button</value>
      <webElementGuid>02ee718a-05de-4ed1-ac46-b4273d44a1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::button[1]</value>
      <webElementGuid>e029c252-5e5e-4038-af25-492edef56481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/button</value>
      <webElementGuid>4496fc1f-fb19-4ede-933a-2ae92e4b8f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'ruangan_id_0001' and (text() = '  Umum3/100' or . = '  Umum3/100')]</value>
      <webElementGuid>84bf95ac-595b-4fd6-b202-e26d1e72fcdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
