<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Umum8100</name>
   <tag></tag>
   <elementGuidId>9366bebb-9965-4611-a1df-b180971fcc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='ruangan_id_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ruangan_id_0001&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70c7a9ab-6236-4023-8983-a77d41a600ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cdbbf1f-e116-473d-9559-2d753bf3c6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ruangan_id_0001</value>
      <webElementGuid>ce951e44-33ac-4113-ad45-e70300b90c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-list btn-info bpoli</value>
      <webElementGuid>6177c790-05b2-445a-8e44-1df207ce5d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setOptionKamar('0001')</value>
      <webElementGuid>4ba5f93c-2c16-4f6b-b5f9-ca40af77466b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdpoli</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>3348dc16-afc1-4cae-8af6-d01a8dc5343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nmpoli</name>
      <type>Main</type>
      <value>POLI UMUM</value>
      <webElementGuid>5af6bf80-808e-48b7-8f3c-e407352f57aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kdruang</name>
      <type>Main</type>
      <value>0001</value>
      <webElementGuid>dcf8a874-6499-4f61-a91d-81d804a9d913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Umum8/100</value>
      <webElementGuid>cfc67f4d-8bcb-4d75-bd24-4588194fd61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info bpoli&quot;]</value>
      <webElementGuid>098d5753-089c-4328-a3eb-890681001f8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='ruangan_id_0001']</value>
      <webElementGuid>b586be12-2a0c-4504-a40f-2efee76fc5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button</value>
      <webElementGuid>8452035c-d67e-41ae-91c0-b10541140e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::button[1]</value>
      <webElementGuid>dd274947-3e3e-4e24-ab83-5b572880429f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/button</value>
      <webElementGuid>e975581a-bd94-496d-97d1-b89343ba380e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'ruangan_id_0001' and (text() = '  Umum8/100' or . = '  Umum8/100')]</value>
      <webElementGuid>e0efea80-11d3-40dd-b98e-ef58ecb1419f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
