<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berhasil Data berhasil disimpan dengan _26328c</name>
   <tag></tag>
   <elementGuidId>909b4afc-ef2a-4afe-b32d-b7667d370974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[@class=', '&quot;', 'col-xs-11 col-sm-4 alert alert-success', '&quot;', ']')])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-11.col-sm-4.alert.alert-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79d4bbde-5229-45a5-adce-4a42842f1fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-notify</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>5c778421-9126-42ce-83df-bb0de4354874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-11 col-sm-4 alert alert-success</value>
      <webElementGuid>30a37a94-d049-4317-a90a-d904cac2178e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>02bdbb36-1fad-4eee-bc70-ac5638ce2e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-notify-position</name>
      <type>Main</type>
      <value>top-center</value>
      <webElementGuid>2ee172cb-80f4-4955-8b60-44b95028daad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>× Berhasil: Data berhasil disimpan dengan ID: 9634!  Perhatian:Data pasien ini belum diverifikasi / belum lengkap.Silahkan verifikasi data pasien di menu Pendaftaran - Pasien &amp; KK!Abaikan pesan ini jika anda akan verifikasi dan lengkapi data pasien di lain waktu.sms notifikasi: pulsa tidak mencukupiData center belum disetting!</value>
      <webElementGuid>20873482-5e11-4a35-aae2-d23716879293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;col-xs-11 col-sm-4 alert alert-success&quot;]</value>
      <webElementGuid>87157e48-a351-4239-9610-6b4be1a238e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[@class=', '&quot;', 'col-xs-11 col-sm-4 alert alert-success', '&quot;', ']')])[1]/following::div[1]</value>
      <webElementGuid>1378e2bd-dd4b-4d03-93be-0b2282963883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::div[4]</value>
      <webElementGuid>77c8845d-fb71-45b3-82a8-ee50ca7f98ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]</value>
      <webElementGuid>3875a54f-5b0e-49a9-ba98-cb91f231c9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '× Berhasil: Data berhasil disimpan dengan ID: 9634!  Perhatian:Data pasien ini belum diverifikasi / belum lengkap.Silahkan verifikasi data pasien di menu Pendaftaran - Pasien &amp; KK!Abaikan pesan ini jika anda akan verifikasi dan lengkapi data pasien di lain waktu.sms notifikasi: pulsa tidak mencukupiData center belum disetting!' or . = '× Berhasil: Data berhasil disimpan dengan ID: 9634!  Perhatian:Data pasien ini belum diverifikasi / belum lengkap.Silahkan verifikasi data pasien di menu Pendaftaran - Pasien &amp; KK!Abaikan pesan ini jika anda akan verifikasi dan lengkapi data pasien di lain waktu.sms notifikasi: pulsa tidak mencukupiData center belum disetting!')]</value>
      <webElementGuid>2997b9eb-bcc0-46ca-a3cb-f286a3441961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
