<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9100</name>
   <tag></tag>
   <elementGuidId>fcd17fe8-90eb-4187-8d1e-0d4b0772f6ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ruangan_id_0001&quot;] > span.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d67c7ab7-f294-4daa-b680-d53aee11eb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>168e68ad-3d88-4c12-b39a-e9946698bca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9/100</value>
      <webElementGuid>7f8cb08a-12dd-4bc6-9f74-87489b967810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info bpoli&quot;]/span[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>c84f8314-e7ea-4285-8621-42b00a7218ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button/span</value>
      <webElementGuid>9a8f6fb7-1317-41f7-9d13-f047b50ffb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[2]</value>
      <webElementGuid>b1e04fb7-3b5b-49fc-8938-84849c14af42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9/100']/parent::*</value>
      <webElementGuid>78d24640-a07e-470a-9a73-fb990b4e2895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button/span</value>
      <webElementGuid>5bfc06fa-9d67-4b10-9068-c1df655b0e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '9/100' or . = '9/100')]</value>
      <webElementGuid>189e7f37-93a7-4204-9528-fffa957a5371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
