<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3100</name>
   <tag></tag>
   <elementGuidId>a40324e3-1b28-47c0-9e42-cec1f2538d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ruangan_id_0001&quot;] > span.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>004a0a95-ec50-41d9-9373-e7ce948b93f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>c8879322-c60e-430e-ad14-d83b64bdb124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3/100</value>
      <webElementGuid>61f76747-48fa-4f8d-855c-16c5edf20e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_pelayanan&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/span[1]/div[@class=&quot;col-sm-3 col-xs-6&quot;]/button[@class=&quot;btn btn-list btn-info bpoli&quot;]/span[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>1e3700ca-8f29-4add-829c-aabba3ce6bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row_pelayanan']/div/div[2]/div/span/div/button/span</value>
      <webElementGuid>f55c5300-0da9-4b05-a6ea-a15fa35ffb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[2]</value>
      <webElementGuid>efbb9a73-67df-4d25-82d3-ad266aa37f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3/100']/parent::*</value>
      <webElementGuid>daa57b65-bd99-4066-8872-d7f33e0a51a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/button/span</value>
      <webElementGuid>25d7a535-2ecb-4a05-ad1f-a2565f7c4d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3/100' or . = '3/100')]</value>
      <webElementGuid>dc0fa618-540d-4de1-a2be-f489ac369b47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
