<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ePuskesmas</name>
   <tag></tag>
   <elementGuidId>e1111842-a2fb-406e-94e5-55f06bfa2cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a3fcdc22-1a19-4792-9242-3be9ab822d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ePuskesmas</value>
      <webElementGuid>cc864f41-bfd2-4718-8c38-b1e8cd5f153d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/nav[@class=&quot;navbar-inner fixed-bottom navbar-light&quot;]/ul[@class=&quot;col-md-4 col-sm-4 col-xs-4 bg-primary-2 green&quot;]/li[1]/ul[@class=&quot;drop-menu menu-4&quot;]/li[@class=&quot;green&quot;]/a[1]/span[1]</value>
      <webElementGuid>8d4ec09b-0b57-4eb4-8d98-48a2085dcbe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      <webElementGuid>b07aca34-1865-46a3-9a31-aae8d2744648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puskesmas . Dinas Kesehatan'])[1]/following::span[1]</value>
      <webElementGuid>4a5e8498-b382-41f4-a680-ad0194fe9670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ePosyandu'])[1]/preceding::span[1]</value>
      <webElementGuid>9879cd43-c5c0-41a5-ae16-7aa8f16038b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eClinic'])[1]/preceding::span[2]</value>
      <webElementGuid>7a1cebcf-9a8a-48ec-9382-a26cb5cb9b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>fec14ce0-ac48-4617-ad51-58ee74f67174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ePuskesmas' or . = 'ePuskesmas')]</value>
      <webElementGuid>e4f2bfe4-eee0-427e-a24a-4ce80c5e627e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
