<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>e508ec99-459c-4336-b550-90c207b9b4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>950b2924-674f-4052-8880-4bfd319cd83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_save</value>
      <webElementGuid>16b137b6-1c03-4f05-9c64-3912e4e8d719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8ed21781-e89d-4ade-847f-db5db04f175b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>390d40ad-5bc1-4f58-ac33-55e131d6eefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return requiredCheck(this);</value>
      <webElementGuid>a20accbf-7c3c-4fed-894c-14af0d4403f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>ea2e6f96-22bf-4d1c-b4f1-7ba35787b14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_save&quot;)</value>
      <webElementGuid>934801a3-08de-437e-863f-cbf1a1380141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_save']</value>
      <webElementGuid>8579eedf-3baa-42bb-9a01-9d4bfdc410aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div[2]/button</value>
      <webElementGuid>39a1f7cb-1f5a-4515-80f5-1e1cbd99fbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Ibu'])[1]/following::button[1]</value>
      <webElementGuid>06ed5a59-55c9-44a3-9713-77aa640c13c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Ayah/KK'])[1]/following::button[1]</value>
      <webElementGuid>fca856a8-653a-44a0-94ee-e68bcc570609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/preceding::button[1]</value>
      <webElementGuid>b3008699-c7b5-4311-8d60-6277f3e2226d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Pasien'])[1]/preceding::button[2]</value>
      <webElementGuid>59a6a356-cab7-4f9b-be24-55c17abd9c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0e43a06a-dd09-4723-9f18-c17d488ca0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_save' and @type = 'submit' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>908bbe13-cb36-422f-8baa-476b01912a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
