<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MEDAN DELI KOTA MEDAN</name>
   <tag></tag>
   <elementGuidId>726d6a8c-31d6-4bc5-b848-d04d5bf64f2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6477532-11ff-4623-b70d-0c035c3f2f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-18</value>
      <webElementGuid>166f55d4-7a0b-45f2-9b65-ae8288704c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dcf711ff-c9b2-4107-8073-d1f5d2271f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>c3dd429c-0505-4e26-8018-92217faf66c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MEDAN DELI KOTA MEDAN</value>
      <webElementGuid>c445ee31-7c86-46d4-bcc4-0cddee6633df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-18&quot;)</value>
      <webElementGuid>8669d451-ea37-4025-8336-135b591dcc90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-18']</value>
      <webElementGuid>fb337cf8-4b8f-4600-942d-3a144ee24bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-8']/li/div</value>
      <webElementGuid>4a5ef61b-4a7a-431d-b0d3-8716eb22329b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA MEDAN'])[1]/following::div[1]</value>
      <webElementGuid>fb628707-3acf-47aa-8acf-d7f0436fe8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[3]/following::div[4]</value>
      <webElementGuid>56eae6ab-1b8e-4ef1-aadd-362655ce5750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDAN DELI'])[1]/preceding::div[2]</value>
      <webElementGuid>454f8732-3923-4d48-ad66-a510763093ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEDAN DELI']/parent::*</value>
      <webElementGuid>344ebc7c-90ad-491b-a779-dd4e789c81f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div</value>
      <webElementGuid>73ca6f6d-42ec-44b2-93d6-f1da498156ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-18' and (text() = 'MEDAN DELI KOTA MEDAN' or . = 'MEDAN DELI KOTA MEDAN')]</value>
      <webElementGuid>d4cd86e7-d4d6-4123-be92-8be87093cacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
