<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KALIMANTAN BARAT</name>
   <tag></tag>
   <elementGuidId>5092ac02-223f-47e9-938b-0273ac1f2864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eaf7aef1-3739-45bf-8a25-d8b43590e75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-20</value>
      <webElementGuid>91b6e82d-40f3-40a8-869d-3e764bc276f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>98518f0b-c376-410d-9df5-cf3e4be59332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>87af7132-4932-4638-bb98-38363fab3fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KALIMANTAN BARAT </value>
      <webElementGuid>cecbe105-ceaf-4c24-81bd-832e8abcb6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-20&quot;)</value>
      <webElementGuid>b6a797f6-b178-4351-8ec1-ed6b6e11f216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-20']</value>
      <webElementGuid>3dce9b92-dedb-4054-bf41-fe4e44453282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-11']/li/div</value>
      <webElementGuid>a9e121c2-eaee-42d0-ae77-bac7dcba1f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GURUSINGA'])[1]/following::div[2]</value>
      <webElementGuid>4f547b6e-dac9-4f4f-85da-d52f01e0eb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BERASTAGI'])[2]/following::div[5]</value>
      <webElementGuid>2c89fb0f-e84b-4b4c-9641-25f218729a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KALIMANTAN BARAT'])[2]/preceding::div[2]</value>
      <webElementGuid>3f884a1c-b5e9-4961-885e-f25146a4aee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KALIMANTAN BARAT'])[3]/preceding::div[3]</value>
      <webElementGuid>0b472f11-ebe7-4e68-b92a-d9038b30b562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KALIMANTAN BARAT']/parent::*</value>
      <webElementGuid>78693087-ba36-4c38-b36d-2bace54a0712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[11]/li/div</value>
      <webElementGuid>f64274e5-c334-44ea-b17e-f512692321fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-20' and (text() = 'KALIMANTAN BARAT ' or . = 'KALIMANTAN BARAT ')]</value>
      <webElementGuid>5c7f91a3-cad1-4961-9575-21d25641ca87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
