<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIANTAR MARIHAT KOTA PEMATANG SIANTAR_1</name>
   <tag></tag>
   <elementGuidId>7269c146-d5ff-4017-a861-4d39c1f6d19d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9d1663e-d5f0-40a5-8e3c-6706917eead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-22</value>
      <webElementGuid>dd50215f-9b21-4f48-bf14-d5e18a9f1606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fb2d00c4-c62f-4e33-b7ea-5a048b5157be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>aafccdc8-e31e-4078-94f8-e1eba4431c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIANTAR MARIHAT KOTA PEMATANG SIANTAR</value>
      <webElementGuid>a40f8625-71b1-41d8-9475-6fe8f1872192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-22&quot;)</value>
      <webElementGuid>f7e07501-551d-43c5-a3dd-90e43efb66d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-22']</value>
      <webElementGuid>80a0b6f2-a1df-4217-adaa-70c5bb07115f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-13']/li/div</value>
      <webElementGuid>047190be-3d17-44d6-bd31-3baf103af9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[1]/following::div[1]</value>
      <webElementGuid>83fbbb57-c779-45fc-9d18-0f3165bf6d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[6]/following::div[4]</value>
      <webElementGuid>fd8db29b-b763-4acc-af4f-4d867b317ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIANTAR MARIHAT'])[1]/preceding::div[2]</value>
      <webElementGuid>1120ed2c-76c9-495a-9215-fec52dcfd5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIANTAR MARIHAT']/parent::*</value>
      <webElementGuid>ca652830-6bf7-40c8-9c25-98e15a099343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[13]/li/div</value>
      <webElementGuid>cb503545-b1ad-434d-af6d-b296615fcc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-22' and (text() = 'SIANTAR MARIHAT KOTA PEMATANG SIANTAR' or . = 'SIANTAR MARIHAT KOTA PEMATANG SIANTAR')]</value>
      <webElementGuid>c46c16c3-0861-48e5-aa3d-ce3a8e0ee96a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
