<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KABUPATEN KARO SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>0db4a511-9200-406e-9364-7d4e7db871b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e4b51d7-9a12-43c9-b708-aa1f804d3426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-17</value>
      <webElementGuid>e3d5ace7-734f-45b7-a552-f1b4508f98e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f50af2ee-d41b-48c4-87f1-e7fe1e163910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>bc6e241d-bd53-4896-81a9-03ba0212191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KABUPATEN KARO SUMATERA UTARA</value>
      <webElementGuid>58be8a28-e9c7-427e-8be9-f33f2a6b52f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-17&quot;)</value>
      <webElementGuid>39be2deb-1b09-4ac6-aeb8-88123118e590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-17']</value>
      <webElementGuid>91882f88-75da-4714-a29c-865cae2ce13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-7']/li/div</value>
      <webElementGuid>b38952f5-0127-4c3f-9623-935a3a64328f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[2]/following::div[1]</value>
      <webElementGuid>8d96e082-21ff-4a13-b02a-c1aa17ed69d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[1]/following::div[4]</value>
      <webElementGuid>790f9c5c-1700-45ee-be01-918b2901fb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN KARO'])[1]/preceding::div[2]</value>
      <webElementGuid>eb5ca1e6-539a-4ba7-a45b-5ea89f1d4880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KABUPATEN KARO']/parent::*</value>
      <webElementGuid>fa04b973-b117-470e-8539-4682d680e7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div</value>
      <webElementGuid>5ad50d62-82b6-49d0-902f-cb4d85f15271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-17' and (text() = 'KABUPATEN KARO SUMATERA UTARA' or . = 'KABUPATEN KARO SUMATERA UTARA')]</value>
      <webElementGuid>066759a1-9aca-40eb-bb07-23001cb7f34d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
