<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIANTAR MARIHAT KOTA PEMATANG SIANTAR</name>
   <tag></tag>
   <elementGuidId>7f58b385-cc78-414a-80d3-4d65c89570bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b9ae8f8-dbe4-41d3-b3bd-d3e5638fad41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-23</value>
      <webElementGuid>d95a1af1-10c9-4c5a-9084-d20a482c43f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f9e6717d-a573-4ba4-b544-7ecfb92cb540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>6bbcf8c1-a0d5-4cf2-a577-f7a0ae36fed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIANTAR MARIHAT KOTA PEMATANG SIANTAR</value>
      <webElementGuid>b3af15a4-9f40-447c-88b8-e9b0218d50c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-23&quot;)</value>
      <webElementGuid>9c7bdb2a-c5b0-4de6-95fe-f775c93b140c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-23']</value>
      <webElementGuid>ac3826e0-2b53-45b7-b047-34752ce3f92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-13']/li/div</value>
      <webElementGuid>235e7f93-4f8b-48cb-b4cf-ded40cbbb36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[1]/following::div[1]</value>
      <webElementGuid>76c156ef-eded-4d1c-a34e-ff34c0687332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[6]/following::div[4]</value>
      <webElementGuid>99b1d9cb-3fe3-4859-b78e-ea729b5911f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIANTAR MARIHAT'])[1]/preceding::div[2]</value>
      <webElementGuid>ac3d245f-faa2-485b-806b-081d0ae8d36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIANTAR MARIHAT']/parent::*</value>
      <webElementGuid>5ddafc34-84cc-48c9-b784-aa409b4f4043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[13]/li/div</value>
      <webElementGuid>d5821338-10d2-4dd0-802f-ae4d90dab40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-23' and (text() = 'SIANTAR MARIHAT KOTA PEMATANG SIANTAR' or . = 'SIANTAR MARIHAT KOTA PEMATANG SIANTAR')]</value>
      <webElementGuid>fbcfa068-c758-42cd-b129-f76d039dfa97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
