<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOTA MEDAN SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>18b2c8d8-2e04-4eaf-b1e2-0db301e14203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15372775-9e99-4098-8d04-138359059b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-17</value>
      <webElementGuid>8c28fc42-d2c6-4953-9a10-e62067c1dd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9a3689ea-f993-4cd0-938a-c198a140706f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>759a531d-4257-40ad-956c-101e771827c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA MEDAN SUMATERA UTARA</value>
      <webElementGuid>5e524427-f3e6-47c1-ab51-d8f35f765701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-17&quot;)</value>
      <webElementGuid>70691912-1a70-4c91-bc5f-0b7840906af0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-17']</value>
      <webElementGuid>1027dd96-9241-4b94-9783-d14f2e897118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-7']/li/div</value>
      <webElementGuid>e8f36639-fbc3-4872-9f98-6a5e93d77824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[2]/following::div[1]</value>
      <webElementGuid>1b9ea7fa-8c17-4f88-854b-b49b840ba739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[1]/following::div[4]</value>
      <webElementGuid>faee5581-99c5-493b-9808-a8e32931bb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA MEDAN'])[1]/preceding::div[2]</value>
      <webElementGuid>d7b475ef-8600-43c3-a2cc-d76063f6648d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOTA MEDAN']/parent::*</value>
      <webElementGuid>4bf43a4e-a546-4f4c-b703-f9eaca254677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div</value>
      <webElementGuid>363a118a-97c4-40d2-ab41-ba219d6c0657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-17' and (text() = 'KOTA MEDAN SUMATERA UTARA' or . = 'KOTA MEDAN SUMATERA UTARA')]</value>
      <webElementGuid>99c2ce5d-bdd1-4675-9840-ee75873bb01f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
