<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BERASTAGI KABUPATEN KARO</name>
   <tag></tag>
   <elementGuidId>5a63b9dd-2f18-4596-b9fb-a4025d39a487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c757d6d7-4603-4ccc-a7d6-863d1fef630a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-18</value>
      <webElementGuid>05b3dd79-8852-4d66-9da9-f3395205d123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa8e0c19-6d2b-497c-96e6-4369b1efc60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>fccd937d-d037-41c7-a180-58814e214cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BERASTAGI KABUPATEN KARO</value>
      <webElementGuid>a25122d2-a5a5-47cd-b6bc-094e975f63c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-18&quot;)</value>
      <webElementGuid>67ef5c4d-7bf9-41b6-b788-c3adb0ff1560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-18']</value>
      <webElementGuid>75119bf8-5c1b-4772-ba53-23d7eedf6aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-8']/li/div</value>
      <webElementGuid>1bc0bd63-4657-4c36-9927-7db695e2a982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN KARO'])[1]/following::div[1]</value>
      <webElementGuid>b52eaafa-ca91-437a-adc4-c232aad9361c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[3]/following::div[4]</value>
      <webElementGuid>e2404f50-00ae-4663-a6aa-9d4528027118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BERASTAGI'])[1]/preceding::div[2]</value>
      <webElementGuid>a72ba645-55a6-443a-ab1a-c2d88a3d4149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BERASTAGI']/parent::*</value>
      <webElementGuid>f70e9d64-7773-4bc9-8392-bb3024c41544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div</value>
      <webElementGuid>1bd11612-c87d-4d9f-bd4c-ca796c78f4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-18' and (text() = 'BERASTAGI KABUPATEN KARO' or . = 'BERASTAGI KABUPATEN KARO')]</value>
      <webElementGuid>e85b8f1e-22ab-4cbe-8e71-8fbe17570c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
