<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOTA PEMATANG SIANTAR SUMATERA UTARA_1</name>
   <tag></tag>
   <elementGuidId>b45b1499-5450-4bb0-9d61-6670c37f404e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9975ee7d-85ce-41c0-aab2-9bf37c02fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-21</value>
      <webElementGuid>e2e7955d-7466-482d-8c51-f97a14484e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>11faa746-2cc0-4cb7-84f0-b96b22c5ef25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>792aa43a-fbcf-4982-b7a5-b2c96d939741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA PEMATANG SIANTAR SUMATERA UTARA</value>
      <webElementGuid>4cadb3de-d5d2-49fc-88af-cff1886728a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-21&quot;)</value>
      <webElementGuid>24e641c3-d8e0-4e77-97be-bdc03111c357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-21']</value>
      <webElementGuid>d5dcf613-bda1-4895-8e41-6bf5710d65e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-12']/li/div</value>
      <webElementGuid>68dcd0a7-e0bb-483f-8fa3-4bcbecc23f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[5]/following::div[1]</value>
      <webElementGuid>6b196689-93c4-4cf8-a48d-64e5e77e20fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[4]/following::div[4]</value>
      <webElementGuid>62913674-dc75-4476-b2cc-84b445203ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[1]/preceding::div[2]</value>
      <webElementGuid>a24806ae-1493-4392-87b1-f07e8f9ac011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOTA PEMATANG SIANTAR']/parent::*</value>
      <webElementGuid>03c15168-0b0b-4aff-8c3d-3ed2ad4377f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[12]/li/div</value>
      <webElementGuid>31535bd7-5bee-4e2e-a0fd-a1ed7af3d252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-21' and (text() = 'KOTA PEMATANG SIANTAR SUMATERA UTARA' or . = 'KOTA PEMATANG SIANTAR SUMATERA UTARA')]</value>
      <webElementGuid>efdd20fb-a6e5-422b-b6af-a5a16df359f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
