<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__input-group</name>
   <tag></tag>
   <elementGuidId>3a4c2204-89cd-4664-a5fc-cee1950a45e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collapseAlamatKtp > div.panel-body.row > div.form-group > div.col-sm-8 > div.input-group</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseAlamatKtp']/div/div[7]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b118c323-977b-4270-94d9-4863a024be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group</value>
      <webElementGuid>9d0e6459-a452-414b-ba05-a5ae34e71145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseAlamatKtp&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;input-group&quot;]</value>
      <webElementGuid>685efb4d-d8c4-479c-ac1c-effc571d2fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseAlamatKtp']/div/div[7]/div/div</value>
      <webElementGuid>58c7649c-8287-4f21-97d3-cff084338952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::div[2]</value>
      <webElementGuid>4fb39a7b-ed07-4a91-bf34-906dfda98eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[20]/preceding::div[1]</value>
      <webElementGuid>66f6bc4f-de6b-40b9-b0a0-4cb3f85d972d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]/div/div</value>
      <webElementGuid>328a7d37-60a6-46af-9eac-ab8ab01ce66a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
