<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SUNGAI BELIUNG PONTIANAK BARAT</name>
   <tag></tag>
   <elementGuidId>c939047b-53b0-4bb1-9a6e-7dbd19cf79bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89a09539-5f02-4059-ab39-853cc4185b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-23</value>
      <webElementGuid>9a98b742-e641-456a-85b0-f0b06522afac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>648573e6-3aa5-4d4d-8fc7-ffa5102e858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>0a4c5eb1-a1c8-43b1-abe4-802113f09cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUNGAI BELIUNG PONTIANAK BARAT</value>
      <webElementGuid>824b1474-fecd-4062-ad6d-4d24710a0a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-23&quot;)</value>
      <webElementGuid>105fdd1c-d20f-4036-ae61-2c5d29024cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-23']</value>
      <webElementGuid>9b6bf59f-824b-4f36-8ce2-9ff70069698d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-14']/li/div</value>
      <webElementGuid>b197ff3f-fe16-4d2d-ba43-0fe3b04a04e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PONTIANAK BARAT'])[1]/following::div[1]</value>
      <webElementGuid>f6908acb-10c0-4012-8204-3eb5505c0137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No search results.'])[1]/following::div[3]</value>
      <webElementGuid>b82d3235-a90a-42af-842b-49f2ddd62b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No search results.'])[2]/preceding::div[1]</value>
      <webElementGuid>b23a45b3-5510-4001-a9a3-2a8895688247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUNGAI BELIUNG']/parent::*</value>
      <webElementGuid>40ba4ec9-8c15-447e-82d7-8aba60723c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li/div</value>
      <webElementGuid>b9a9f221-1e16-4345-8926-a7bf0bd92812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-23' and (text() = 'SUNGAI BELIUNG PONTIANAK BARAT' or . = 'SUNGAI BELIUNG PONTIANAK BARAT')]</value>
      <webElementGuid>e4c8d0f5-de4b-4a32-b538-98eccfaeedb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
