<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOTA PEMATANG SIANTAR SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>4dd1d68f-594e-47ef-9dfb-fe2e756e5bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f54a3f6-8730-4751-b8ed-819288eca15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-22</value>
      <webElementGuid>e4c7916e-a2ca-466d-8e49-aeaabd238148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9fa701b3-e9e2-4c4a-8b2a-20227b6a3c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>47dbdc31-ef05-4675-9f1e-ee034b7832d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA PEMATANG SIANTAR SUMATERA UTARA</value>
      <webElementGuid>290acbe4-b523-438e-babb-0ba8731b855d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-22&quot;)</value>
      <webElementGuid>16d7de8b-531f-4950-bdfd-7b2586352307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-22']</value>
      <webElementGuid>3f904559-a78e-43a6-b6e1-80622cd535cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-12']/li/div</value>
      <webElementGuid>43cd831c-1eef-42f9-996f-df46909800ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[5]/following::div[1]</value>
      <webElementGuid>ced3eef9-71c3-422f-91d6-f277ad2f969e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[4]/following::div[4]</value>
      <webElementGuid>812654bf-977a-49a4-8a9f-c5bc56cb6b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[1]/preceding::div[2]</value>
      <webElementGuid>1150bb66-a03f-464a-9bbf-cbecb9889221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOTA PEMATANG SIANTAR']/parent::*</value>
      <webElementGuid>2f609fc0-c588-4202-a258-d0e33e65fd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[12]/li/div</value>
      <webElementGuid>6f56f6ca-d2ac-4185-aa44-8f69fefe984f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-22' and (text() = 'KOTA PEMATANG SIANTAR SUMATERA UTARA' or . = 'KOTA PEMATANG SIANTAR SUMATERA UTARA')]</value>
      <webElementGuid>f78c6c4c-aec3-44f7-bda4-bad03c83f1cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
