<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PARDAMEAN SIANTAR MARIHAT</name>
   <tag></tag>
   <elementGuidId>993d24d3-5484-47e0-9d04-2d1116fd5e81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aeae6126-ff98-48c2-91c2-1b02ac961cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-24</value>
      <webElementGuid>d2f1ef72-2b82-46cf-85b8-da9b44efae8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6c528660-94b4-49e7-97be-ce79a32b1951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>7bed0cfe-3d84-41ea-a2b9-dd26f1950e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PARDAMEAN SIANTAR MARIHAT</value>
      <webElementGuid>6bbbb1d5-53dd-4829-80ed-9e173dcc6269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-24&quot;)</value>
      <webElementGuid>2338c357-8255-4c1f-ad99-4de8b88c8030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-24']</value>
      <webElementGuid>a0192755-39e7-41e6-b9af-a9c28ba5e46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-14']/li/div</value>
      <webElementGuid>218f9541-9df5-4554-b72e-4868923d7b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIANTAR MARIHAT'])[1]/following::div[1]</value>
      <webElementGuid>f3fdd9b8-4ab0-4aaf-bdb6-5e4aa7c6df0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[2]/following::div[4]</value>
      <webElementGuid>c91824de-fade-4ce6-8161-81da27399698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PARDAMEAN'])[1]/preceding::div[2]</value>
      <webElementGuid>2d4a9749-5552-44de-80d6-25324e6fa407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PARDAMEAN']/parent::*</value>
      <webElementGuid>76d00a1b-0508-498a-bad8-90c4477fb57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li/div</value>
      <webElementGuid>82aab87b-cabc-4a7b-a346-17f5e72df776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-24' and (text() = 'PARDAMEAN SIANTAR MARIHAT' or . = 'PARDAMEAN SIANTAR MARIHAT')]</value>
      <webElementGuid>3f692767-e143-4eda-8f12-2c6fcfcf3c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
