<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PONTIANAK BARAT KOTA PONTIANAK</name>
   <tag></tag>
   <elementGuidId>183c39bb-31d6-4412-92d4-ffbe820056e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6cd0a7b1-2ef8-4bb4-a364-402c8f8ad9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-22</value>
      <webElementGuid>41052388-6b9f-42c7-a244-a6d6c4ce6831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>59325c8e-fd49-41d2-8243-4d196a7c026e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>154f94c0-4a81-45f2-bfac-8cf7a47fe3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PONTIANAK BARAT KOTA PONTIANAK</value>
      <webElementGuid>3b222685-a2f6-45e9-aa69-6706a9b1b53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-22&quot;)</value>
      <webElementGuid>767e6715-2b45-4006-9d30-65b51600eb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-22']</value>
      <webElementGuid>be7220a0-5576-45aa-bee5-1e24776cab36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-13']/li/div</value>
      <webElementGuid>50f6b504-f7bb-43f5-b25c-efe5db494b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PONTIANAK'])[1]/following::div[1]</value>
      <webElementGuid>9b9aded9-4f92-4c86-96e9-45e1f0500473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KALIMANTAN BARAT'])[4]/following::div[4]</value>
      <webElementGuid>54946972-1335-4417-bc9d-f6bffbd42cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No search results.'])[1]/preceding::div[1]</value>
      <webElementGuid>77138941-4d17-4d1b-84ac-1b813c89450a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PONTIANAK BARAT']/parent::*</value>
      <webElementGuid>4471e3f7-f058-4313-9f4e-65e6b71db990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[13]/li/div</value>
      <webElementGuid>55a22e60-ab5f-4727-b2c4-09d018018c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-22' and (text() = 'PONTIANAK BARAT KOTA PONTIANAK' or . = 'PONTIANAK BARAT KOTA PONTIANAK')]</value>
      <webElementGuid>fa804a63-f395-4a19-b8c8-20420c4d398d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
