<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PETANIPERKEBUNAN</name>
   <tag></tag>
   <elementGuidId>53f11e6e-cd67-4ec4-8d79-40bb243f6af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-26']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d6a8c15-92f1-4b7c-a5cd-71259e802a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-26</value>
      <webElementGuid>81b3b4b4-b85c-4c73-87a6-0b82d8843a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9cc46fbc-611e-4308-ac16-c559c943bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>3bc12b47-bfbe-4f0e-a0c7-04fae9bf1bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PETANI/PERKEBUNAN</value>
      <webElementGuid>8c62717d-f94f-4575-8159-58e7e015497e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-26&quot;)</value>
      <webElementGuid>4e3e995a-6e09-4833-950e-5d6294638fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-26']</value>
      <webElementGuid>92e3a378-0b70-43b1-9646-d08e8fd8ecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-3']/li/div</value>
      <webElementGuid>60542dee-d74d-4642-a3bc-44a72e1272e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[2]/following::div[3]</value>
      <webElementGuid>438f5ffa-a6f2-47e4-abeb-90e03be3a0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Pasien'])[1]/following::div[3]</value>
      <webElementGuid>0a9417d2-5471-42cb-bee0-04cd53d4e768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETANI/PERKEBUNAN'])[2]/preceding::div[2]</value>
      <webElementGuid>57ad7220-d00b-438e-8d50-dffd26f69fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETANI/PERKEBUNAN'])[3]/preceding::div[4]</value>
      <webElementGuid>6b20f09b-f094-4ff0-9913-f46d8da4e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PETANI/PERKEBUNAN']/parent::*</value>
      <webElementGuid>34f48565-3f4e-4ce6-9871-d429e309f49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/div</value>
      <webElementGuid>c722dde2-c1c5-43ab-b209-df55c3e9707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-26' and (text() = 'PETANI/PERKEBUNAN' or . = 'PETANI/PERKEBUNAN')]</value>
      <webElementGuid>51e27455-e0cb-4b65-a365-cb1cc6debbbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
