<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PARDAMEAN SIANTAR MARIHAT_1</name>
   <tag></tag>
   <elementGuidId>4f85b6e7-f6be-42f9-8059-b66f4911cf1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-25']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>583a2826-d869-462a-b270-c9b2fe5aa384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-25</value>
      <webElementGuid>dfb757b6-f617-4f9c-a11f-21e7c5a152f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e2a49fdf-d61f-4cf5-9e92-1ebab2c98c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>a5bf2102-a036-4b0f-a104-e8d7d84c2dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PARDAMEAN SIANTAR MARIHAT</value>
      <webElementGuid>620836cd-2a37-4d97-86a5-f1edae53834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-25&quot;)</value>
      <webElementGuid>79ac0889-5a00-4446-aaeb-3ce1a1736add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-25']</value>
      <webElementGuid>8aba27a7-fe7a-46ef-a12b-63debd026845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-14']/li/div</value>
      <webElementGuid>4844aced-c06e-41b6-b006-ebab43c254ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIANTAR MARIHAT'])[1]/following::div[1]</value>
      <webElementGuid>04aef02b-d8fe-42e3-80c6-499e751b7c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA PEMATANG SIANTAR'])[2]/following::div[4]</value>
      <webElementGuid>3927c1f1-1447-432b-8554-07a4578666b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PARDAMEAN'])[1]/preceding::div[3]</value>
      <webElementGuid>a85c0488-e4b2-40c1-bb55-fde2d2af3ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PARDAMEAN']/parent::*</value>
      <webElementGuid>680d6a16-5cf8-4163-acd3-ddf660cdcda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li/div</value>
      <webElementGuid>cd1d7a0f-cd82-41c7-a772-ad6e0ef38908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-25' and (text() = 'PARDAMEAN SIANTAR MARIHAT' or . = 'PARDAMEAN SIANTAR MARIHAT')]</value>
      <webElementGuid>2251ca55-a7b9-4a52-9bb4-5888e38f5781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
