<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ktp_propinsi_nama</name>
   <tag></tag>
   <elementGuidId>720691e6-50ee-4cd6-aa31-b5796270af7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ktp_propinsi_nama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ktp_propinsi_nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f1ed0a2-9d42-439c-b388-0a3c0f89a0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecc5bb79-2e2e-44ea-a97b-d373f27e281c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm uppercase ui-autocomplete-input</value>
      <webElementGuid>7859a887-bebb-4bc3-934b-eca8eca2e2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ktp_propinsi_nama</value>
      <webElementGuid>82e2b36b-89b8-4769-8c4a-31fcdbdd17f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Propinsi</value>
      <webElementGuid>5151ae8f-941f-4ff2-a881-a861c1deb95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>dc30304e-4f74-4014-b3fe-82b0987b4df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0fc89f66-8802-4ffc-87a2-3daaeb4d5d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseAlamatKtp&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/input[@class=&quot;form-control input-sm uppercase ui-autocomplete-input&quot;]</value>
      <webElementGuid>b918776a-3160-484c-9b3c-87628855f687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ktp_propinsi_nama']</value>
      <webElementGuid>986de011-c2e6-4868-a58e-69113be4e404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseAlamatKtp']/div/div/div/input[2]</value>
      <webElementGuid>10cb2795-3425-463a-8b02-40a57876292f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input[2]</value>
      <webElementGuid>682ae08f-65b3-4e0f-98cf-8fe5e22fb25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ktp_propinsi_nama' and @placeholder = '🔍 Nama Propinsi']</value>
      <webElementGuid>0cdddf1a-000d-4492-83e0-8115402aaa24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
