<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kota_nama</name>
   <tag></tag>
   <elementGuidId>703e00e4-1fb7-4200-8c18-fd33e2103469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kota_nama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kota_nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a19e3485-86d9-49f3-ba89-95b945f3fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41238cec-ac21-44cf-8961-82265e7284f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm uppercase ui-autocomplete-input</value>
      <webElementGuid>d2f9ca11-62a9-4618-bb31-37995224b0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_nama</value>
      <webElementGuid>4fc9eb5f-0d23-4f34-b587-b87884ff2c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Kota / Kabupaten</value>
      <webElementGuid>c2c926f3-a3f0-4b69-abbc-eb0128f233c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>c696ac82-2080-4ca6-a364-c087f3afc4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b3d58c1-17e1-443f-b0e5-635b806a0b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;panel panel-default container-fluid&quot;]/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/input[@class=&quot;form-control input-sm uppercase ui-autocomplete-input&quot;]</value>
      <webElementGuid>903cda14-850a-4550-82a7-e0a5b01abbe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kota_nama']</value>
      <webElementGuid>968cf5f0-7e88-4fe3-a79d-892fbef85d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[2]/div[6]/div[2]/div[2]/div/input[2]</value>
      <webElementGuid>0e53062e-5c18-4cd4-8bfb-4bc78d536317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input[2]</value>
      <webElementGuid>9daa4c6d-3f19-445a-8892-c9e0333a56ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kota_nama' and @placeholder = '🔍 Nama Kota / Kabupaten']</value>
      <webElementGuid>9f6b7aff-3f92-49c3-9f1a-1a9004d99d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
