<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__MPasientanggal_lahir</name>
   <tag></tag>
   <elementGuidId>24f8634a-31eb-46cf-9a1b-b221e3ee0072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>556e68c8-82b7-445b-8e45-1e68eb3cd24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>791d662a-821b-4ea7-91d2-3c9a3d75a053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>e59c50ee-49e5-401e-8c70-a40625682c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>f8a31f3d-414b-426b-a3a5-6b48f46b2501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[tanggal_lahir]</value>
      <webElementGuid>2801e982-bab0-4ab5-a12f-a1826c6a479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>4a9c2c31-8756-41a0-89ca-5525e19e555e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bfe8dcc4-3949-4f69-8625-7ee6f2e06c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggal_lahir&quot;)</value>
      <webElementGuid>4e992930-1bcb-40b6-9370-8f4c582dd56b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggal_lahir']</value>
      <webElementGuid>e3b6837d-4d3d-46cb-b394-13fa29d53ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div/div[11]/div/div/input</value>
      <webElementGuid>016a79b8-9c0f-4b19-b439-879d1508f084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>a320885a-5e37-4c27-b044-8793eaf8898f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tanggal_lahir' and @name = 'MPasien[tanggal_lahir]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>94731bcf-a9d7-4e26-b46d-0bd58713392a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
