<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih -                           _05c17e</name>
   <tag></tag>
   <elementGuidId>b00755bc-e1c1-4cb4-aa94-9f5baec39c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;MPasien[agama]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='MPasien[agama]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2b4c045-4e69-414c-b9ab-f3f679729c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>1a7c9484-60ee-45c1-ae84-23b5cb48c1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[agama]</value>
      <webElementGuid>ccc3ec5e-5565-4a95-b820-6ca961084a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>46ba77f9-a254-4cab-bf70-bd229a326cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            - Pilih -
                                                                                                ISLAM
                                                                    KATOLIK
                                                                    KRISTEN
                                                                    HINDU
                                                                    BUDDHA
                                                                    KONGHUCU
                                                                    LAINNYA
                                                                                    </value>
      <webElementGuid>3a60e0c9-e780-43b7-b42d-d876a1ebcbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/select[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>574ddec5-a4cd-4598-9c3b-b546056c07aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='MPasien[agama]']</value>
      <webElementGuid>71531e54-107f-42cd-b3a1-5764e892be4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[3]/div[5]/div/select</value>
      <webElementGuid>1a538838-a5a2-4dbc-ab55-848dcc4a4457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[21]/following::select[1]</value>
      <webElementGuid>2ae6f1a4-fde7-4869-a359-ce9f30beffbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[22]/preceding::select[1]</value>
      <webElementGuid>27afe28a-f18e-4038-af2a-932cbdb1cc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>5f725909-ef70-4f79-a7ee-52a54c05aaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'MPasien[agama]' and (text() = '
                            - Pilih -
                                                                                                ISLAM
                                                                    KATOLIK
                                                                    KRISTEN
                                                                    HINDU
                                                                    BUDDHA
                                                                    KONGHUCU
                                                                    LAINNYA
                                                                                    ' or . = '
                            - Pilih -
                                                                                                ISLAM
                                                                    KATOLIK
                                                                    KRISTEN
                                                                    HINDU
                                                                    BUDDHA
                                                                    KONGHUCU
                                                                    LAINNYA
                                                                                    ')]</value>
      <webElementGuid>9ce1e9d1-8401-4d37-80f6-4e7f2c2869a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
