<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih -                           _73a496</name>
   <tag></tag>
   <elementGuidId>71b7cf05-3b07-4cf7-984f-2f623040b30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;MPasien[warganegara]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='MPasien[warganegara]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>035eb379-7f8b-48e5-ab9c-8f9932e562cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm warganegara</value>
      <webElementGuid>98b6e13c-a3fe-4d10-ae65-fd05643d1367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[warganegara]</value>
      <webElementGuid>2c5271df-c79e-44c8-a086-595a71e3a2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f9331944-2243-44c2-a524-c5473971d57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    </value>
      <webElementGuid>c97cfc22-7dbb-40e9-a3a8-38a24b944117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/select[@class=&quot;form-control input-sm warganegara&quot;]</value>
      <webElementGuid>5d00ccbc-b312-41bc-b129-ce83fe058ca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='MPasien[warganegara]']</value>
      <webElementGuid>5b9d4edf-6e7d-43d5-838b-b7338b9514e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[3]/div[10]/div/select</value>
      <webElementGuid>4003a2fc-9c83-4bee-94fd-d039a448b175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[25]/following::select[1]</value>
      <webElementGuid>914d36a2-9d6d-4f75-a9d7-bdc68e7ba960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Paspor'])[1]/preceding::select[1]</value>
      <webElementGuid>02e7e1ea-6606-4055-9779-d7bf246cedf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Ayah/KK'])[1]/preceding::select[1]</value>
      <webElementGuid>d7f337c2-f8b4-4830-a3a2-d702fa81b664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>a22f5b46-7e3c-439b-872e-15f6c6c95086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'MPasien[warganegara]' and (text() = '
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    ' or . = '
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    ')]</value>
      <webElementGuid>2bb8feba-ad18-405a-a8b3-a06d5adda6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
