<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anamnesa</name>
   <tag></tag>
   <elementGuidId>49e9b7a8-b603-4c37-a3a2-ad9becdaed63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_anamnesa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_anamnesa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73daebf4-26d5-498a-a5e6-9227fc1bd071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/anamnesa/create/9652?from='pelayanan'&amp;action='edit'</value>
      <webElementGuid>aa2bbbbf-9e71-4371-8631-95dc52471515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_anamnesa</value>
      <webElementGuid>7847d613-a92a-4c4e-abd0-aa3e3f5f8d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>2b4f0b6b-487f-4d41-84db-14019275f85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anamnesa</value>
      <webElementGuid>c0e4274c-9656-473b-9f43-101ac3c5efc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_anamnesa&quot;)</value>
      <webElementGuid>971a2a54-3631-4c08-929b-141007337892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_anamnesa']</value>
      <webElementGuid>cb74e742-1320-49d1-8f09-4bcef6bf893b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[2]/div[2]/div/a[2]</value>
      <webElementGuid>e83726fb-2870-4ce6-a1c3-f07bf15d4faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anamnesa')]</value>
      <webElementGuid>5d7e7ab1-0b71-4b32-80c6-58693f31fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[2]/following::a[1]</value>
      <webElementGuid>9a70f48e-1fcb-4c18-8fbf-10b6e504dd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[2]/following::a[2]</value>
      <webElementGuid>0e4cfdad-2cfa-4486-8948-5ff403e2df55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosa'])[2]/preceding::a[1]</value>
      <webElementGuid>53427ee0-7b2b-4bda-93fb-37c37fc819cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[2]/preceding::a[2]</value>
      <webElementGuid>c4086cc5-c826-4a21-ab26-099224df4fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anamnesa']/parent::*</value>
      <webElementGuid>b34f8c8f-73f9-4873-805f-131331213b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://demo.epuskesmas.id/anamnesa/create/9652?from='pelayanan'&amp;action='edit'&quot;)]</value>
      <webElementGuid>2a2c6dc3-6aef-4351-9c78-3aa092f7c362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>accb46ea-c5ba-42ef-9057-138ffde2886b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;https://demo.epuskesmas.id/anamnesa/create/9652?from=&quot; , &quot;'&quot; , &quot;pelayanan&quot; , &quot;'&quot; , &quot;&amp;action=&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot;) and @id = 'button_anamnesa' and (text() = 'Anamnesa' or . = 'Anamnesa')]</value>
      <webElementGuid>501015d5-d65f-4224-9a96-646cb4e48261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
