<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resep</name>
   <tag></tag>
   <elementGuidId>eb96afd7-0780-4a8c-9dff-64e9b67654be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_resep']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_resep</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9182d16f-6dc4-4091-a472-086c410f6e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/resep/create/9654?from='pelayanan'&amp;action='edit'</value>
      <webElementGuid>e3267da5-bd14-4715-b119-a0f7f739e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_resep</value>
      <webElementGuid>cf37a99c-97cc-4299-9042-7ba90c67b0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>907069d6-6014-4441-a089-53433c592538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resep</value>
      <webElementGuid>e3307ed3-eb07-465c-bb6f-5c3b857e09b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_resep&quot;)</value>
      <webElementGuid>f494b734-c4b3-43fd-a5b6-94759531f390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_resep']</value>
      <webElementGuid>bc5f41cc-dcbe-4de2-8ce5-317f4fbdc254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[2]/div[2]/div/a[4]</value>
      <webElementGuid>f5732791-5e15-452f-aed8-084970693a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Resep')])[3]</value>
      <webElementGuid>3c4fc281-8df4-4259-af1f-33672d2049ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosa'])[2]/following::a[1]</value>
      <webElementGuid>4a632d41-c9ca-4de1-8c4c-cd769dbc2eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anamnesa'])[1]/following::a[2]</value>
      <webElementGuid>b0806cfe-5f05-4388-8dbe-d2eec8b9bdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alkes'])[2]/preceding::a[1]</value>
      <webElementGuid>dc367e36-4f48-42ac-ade0-c7f694ab3b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obat/Alkes'])[1]/preceding::a[2]</value>
      <webElementGuid>16507879-b60c-4c3c-9802-7c3b4801fe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://demo.epuskesmas.id/resep/create/9654?from='pelayanan'&amp;action='edit'&quot;)]</value>
      <webElementGuid>6e023143-97e5-4b56-9e9f-b05f853ddf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>3ae1d5a6-0156-4e11-a7ae-aebdaa274238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;https://demo.epuskesmas.id/resep/create/9654?from=&quot; , &quot;'&quot; , &quot;pelayanan&quot; , &quot;'&quot; , &quot;&amp;action=&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot;) and @id = 'button_resep' and (text() = 'Resep' or . = 'Resep')]</value>
      <webElementGuid>8647496e-dcc4-45f0-ba5f-55883a2b96ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
