<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MEDAN HELVETIA KOTA MEDAN</name>
   <tag></tag>
   <elementGuidId>c73a427e-6901-4c27-970c-08d56ed8bf06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f29d099e-ccc3-4353-a2b7-125201271ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-30</value>
      <webElementGuid>cb641f60-4daf-4305-978f-ab0e95ba9975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>552ec1cd-0239-4367-8e39-d06846c4f040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>3befdf64-7578-4703-ac3e-60291a9ee207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MEDAN HELVETIA KOTA MEDAN</value>
      <webElementGuid>b386feca-5d77-4880-9ab0-a28383ff0298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-30&quot;)</value>
      <webElementGuid>588087a6-4ab6-4a27-8005-801c1823a2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-30']</value>
      <webElementGuid>620a0a7c-6436-4f9f-96ae-740cdbaeff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-8']/li/div</value>
      <webElementGuid>dea048a2-5fb0-4c47-be38-77a265bfc5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA MEDAN'])[1]/following::div[1]</value>
      <webElementGuid>4e0b2754-5147-4c9a-bb04-f030a9856810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[5]/following::div[4]</value>
      <webElementGuid>25d5ad1f-71b7-4f71-a6ad-ada020ef7c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDAN TUNTUNGAN'])[1]/preceding::div[2]</value>
      <webElementGuid>b8fcbc7b-45f3-4a66-b03c-ba5990bfedb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEDAN HELVETIA']/parent::*</value>
      <webElementGuid>c33cb9e7-2b0b-4d6f-a47e-afdd5138e2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div</value>
      <webElementGuid>3a019c2d-7026-495f-9684-9f904db606e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-30' and (text() = 'MEDAN HELVETIA KOTA MEDAN' or . = 'MEDAN HELVETIA KOTA MEDAN')]</value>
      <webElementGuid>7a299439-e2ca-443a-ad24-4813fde61dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
