<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HELVETIA TIMUR MEDAN HELVETIA</name>
   <tag></tag>
   <elementGuidId>143a7c3b-4160-4b27-b86c-73cd0cd6ec54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf5043de-b2d8-4b8b-9a63-a8ff0f7f5843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-31</value>
      <webElementGuid>dc9b2ceb-9d98-489f-84a9-ed43d8812608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4d078a1a-fa73-43a9-b2c9-f70703489e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>b4c42f2b-02b5-4845-be71-7c50753b3a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HELVETIA TIMUR MEDAN HELVETIA</value>
      <webElementGuid>59d36a2c-62bb-4cee-b9c9-d97ac07c8461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-31&quot;)</value>
      <webElementGuid>0063fbdf-6992-4ed3-a2b5-72db25f3e8b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-31']</value>
      <webElementGuid>aa049cea-0a1b-497f-a8c6-579b1ac6f9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-9']/li/div</value>
      <webElementGuid>8917f018-445c-404b-a3b1-ed3aa5c7fe27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDAN HELVETIA'])[1]/following::div[1]</value>
      <webElementGuid>6a45e383-71fb-48e3-a66f-42dc2b6b184a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDAN TUNTUNGAN'])[1]/following::div[3]</value>
      <webElementGuid>07ac56af-84a2-4924-9850-926e3d5abe0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HELVETIA TIMUR']/parent::*</value>
      <webElementGuid>cad91843-e03d-4b72-b011-4aa4fe964bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[9]/li/div</value>
      <webElementGuid>3cb32981-889b-4872-b535-f6a20c50e5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-31' and (text() = 'HELVETIA TIMUR MEDAN HELVETIA' or . = 'HELVETIA TIMUR MEDAN HELVETIA')]</value>
      <webElementGuid>46ce939a-ad0e-4346-9f41-56701ab682d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
