<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PELAJARMAHASISWA</name>
   <tag></tag>
   <elementGuidId>681810ff-61f1-478d-bd99-50f92fa7a1a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfe2dac9-09f0-4795-873c-da6b3d198c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-34</value>
      <webElementGuid>01b476c0-d6a8-455a-96f6-2f01a0eae19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bf023cfb-59c0-4bdd-b32d-3fa51fe6a3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>7749e995-59d6-4d67-9559-436034000b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PELAJAR/MAHASISWA</value>
      <webElementGuid>68e40aa0-181c-4391-8d34-54a674c8084c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-34&quot;)</value>
      <webElementGuid>9ef899f4-c1ce-465f-a39b-42fc15ecbed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-34']</value>
      <webElementGuid>6def96e8-d9a5-4d18-995e-b41074ab7203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-3']/li/div</value>
      <webElementGuid>a638ec60-2af6-4bf1-a08e-ac97fd06fe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[2]/following::div[3]</value>
      <webElementGuid>9a4f2599-fc60-4b60-b07d-1bcaf6497e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Pasien'])[1]/following::div[3]</value>
      <webElementGuid>652cfc23-14c3-44cd-b36e-2a78f98e24fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PELAJAR/MAHASISWA'])[2]/preceding::div[2]</value>
      <webElementGuid>51bae529-61a7-4a1f-9b72-1592f4208229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA BARAT'])[1]/preceding::div[6]</value>
      <webElementGuid>0b45bc12-bcb6-44f2-8b69-9bf12515f803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PELAJAR/MAHASISWA']/parent::*</value>
      <webElementGuid>04bc9f24-efb5-42af-81ec-c70731e63543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/div</value>
      <webElementGuid>31585890-af11-45fc-b1aa-f5e1ca969e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-34' and (text() = 'PELAJAR/MAHASISWA' or . = 'PELAJAR/MAHASISWA')]</value>
      <webElementGuid>50c92c14-eb3f-48dc-b912-06353ea245ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
