<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>3c19b936-f001-47d3-8040-e9f987accd95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32870cb3-980f-4378-b36f-e136e5a6f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-18</value>
      <webElementGuid>dbb20f59-3a1a-4e2f-a8d6-45939d8eb3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3bb4528f-9fbc-4b02-9a2e-6b4b364e510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>ecddfea8-d5b5-4ffe-8c16-77e38ec8a445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUMATERA UTARA </value>
      <webElementGuid>c09c2333-be03-4400-a551-e5bec2a24e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-18&quot;)</value>
      <webElementGuid>81c270cd-7f06-4f3b-b86f-a9ad4876e8e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-18']</value>
      <webElementGuid>d18cc890-30c9-4784-8ed0-4d562ac8380d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-6']/li[3]/div</value>
      <webElementGuid>898bbff2-7ce5-4ad9-a6bc-f6e8ee9f8f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA SELATAN'])[1]/following::div[1]</value>
      <webElementGuid>370ccd0f-f4d4-404c-8be1-a73b3d70f953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA BARAT'])[1]/following::div[2]</value>
      <webElementGuid>99500cd0-f848-43c8-a405-da29051c7edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA BARAT'])[2]/preceding::div[2]</value>
      <webElementGuid>6eb52d49-7261-4924-a2f1-8e8584c1b4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA SELATAN'])[2]/preceding::div[3]</value>
      <webElementGuid>3ae99c1d-0ef4-4e28-9a66-67bf78154590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUMATERA UTARA']/parent::*</value>
      <webElementGuid>dd7ce1b9-9904-4522-bf84-b86dc95c81b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>223287d8-a4c8-4dc7-8c0e-62c104cf1a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-18' and (text() = 'SUMATERA UTARA ' or . = 'SUMATERA UTARA ')]</value>
      <webElementGuid>98123243-f818-4685-b183-19a946298670</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
