<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KOTA MEDAN SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>8bee1303-b3f9-4111-bc50-1e7214396dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c629c959-295c-4dc5-ba76-aaf380613d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-19</value>
      <webElementGuid>5968f73b-7126-4a25-ad5a-7e11a08ea9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f65b5095-2efc-4fc7-9a7b-a1a250ca6ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>92cb45dd-0839-43dd-8d17-8e14fe05e202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KOTA MEDAN SUMATERA UTARA</value>
      <webElementGuid>1eacfded-d98b-4a22-8adf-9ee7b80e7026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-19&quot;)</value>
      <webElementGuid>dcdb1cec-7c84-4f6c-8194-b23eba606ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-19']</value>
      <webElementGuid>d87aa64a-647f-4821-bb4e-7c5ecaac76ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-7']/li/div</value>
      <webElementGuid>1e653c8d-8241-4bfc-9d92-2389f00c6d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[4]/following::div[1]</value>
      <webElementGuid>702bc06c-be72-4d4d-9a44-f39748bfac0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA SELATAN'])[4]/following::div[2]</value>
      <webElementGuid>8e767306-48aa-4bf5-a3a6-d295d14ce9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA MEDAN'])[1]/preceding::div[2]</value>
      <webElementGuid>a2ef3130-0618-4ec8-8f71-f6c6845a156d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KOTA MEDAN']/parent::*</value>
      <webElementGuid>0c03692d-389a-42bf-b429-361bcabf9bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div</value>
      <webElementGuid>c3aa3aaf-6cbd-4ab3-a2b7-a51fb409c0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-19' and (text() = 'KOTA MEDAN SUMATERA UTARA' or . = 'KOTA MEDAN SUMATERA UTARA')]</value>
      <webElementGuid>46a96616-b84b-457c-a819-ad35c019f949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
