<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_SUMATERA UTARA_fa fa-map-marker</name>
   <tag></tag>
   <elementGuidId>96b47a09-4d71-4aa7-b357-d9547f3f3a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-19']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-map-marker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>40cdd207-f982-43aa-953b-78d38cbbf48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-map-marker</value>
      <webElementGuid>9ce437d6-0736-493a-b6f2-0cc8c420e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-19&quot;)/i[@class=&quot;fa fa-map-marker&quot;]</value>
      <webElementGuid>1f119939-3856-4b63-868e-37ed58dd46f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-19']/i</value>
      <webElementGuid>1bc3d5fb-c490-4000-8c67-dcb956e840b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>a2e8e64e-026c-40b4-b561-9d7ef7f3151a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
