<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir_MPasientanggal_lahir</name>
   <tag></tag>
   <elementGuidId>6692c0dd-71ec-42ca-af94-149c436f27e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>418ba87f-cc89-459d-91dc-69c47bbddec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6f378ef-79a4-41c5-a91f-8abdf30fba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>b5acc360-2faf-4b48-911d-216baefbca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>e8664696-7abd-4d2f-85bc-72f373229795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[tanggal_lahir]</value>
      <webElementGuid>9ed4b367-edd6-495f-8bb5-13b292b6c33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>7edc8453-584c-46b6-89f6-de85a762c181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggal_lahir&quot;)</value>
      <webElementGuid>0f13e7ab-c895-4638-96f8-799fc761aafb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggal_lahir']</value>
      <webElementGuid>c9a2995d-3d8d-4732-ae5e-50aa3bd90f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div/div[11]/div/div/input</value>
      <webElementGuid>36162dbb-51ee-4d59-b85d-bc7c933f13d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>4a5ce192-4b14-4836-921b-d3589ae59ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tanggal_lahir' and @name = 'MPasien[tanggal_lahir]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>17ccd4c8-ab25-4c3c-9cb4-241dd0c3bdac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
