<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__propinsi_nama</name>
   <tag></tag>
   <elementGuidId>70ac86a2-0ef6-4403-9a88-d9a2f341bce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='propinsi_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;propinsi_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04295036-93e6-4ef4-bec0-527ef394044f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbb467f6-e245-4f44-8537-ec8064b37fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm uppercase ui-autocomplete-input</value>
      <webElementGuid>5a161018-bac3-4d79-a3e8-5734a4e0fa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propinsi_nama</value>
      <webElementGuid>b6855d53-c7c6-4419-9652-c8eb275a19c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Propinsi</value>
      <webElementGuid>2a507fdb-2586-4fee-baf6-8921bfb997d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>0f7444c0-6e38-41af-938e-231a3d8b3304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed658a26-f8a9-499e-8a5f-fbf1dada201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;panel panel-default container-fluid&quot;]/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/input[@class=&quot;form-control input-sm uppercase ui-autocomplete-input&quot;]</value>
      <webElementGuid>07f416ee-176d-4f9a-849d-ba4633c75c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='propinsi_nama']</value>
      <webElementGuid>8ec560c3-93b9-4c33-8513-4a03f0d92dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[2]/div[6]/div[2]/div/div/input[2]</value>
      <webElementGuid>db9b77a2-78f5-4251-925c-6b8dbd6b893f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>96a007da-1a47-40ef-b507-8f8d3818d41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propinsi_nama' and @placeholder = '🔍 Nama Propinsi']</value>
      <webElementGuid>0532747e-f6f1-4d6b-8252-e3d57b5b38dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
