<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kecamatan_nama</name>
   <tag></tag>
   <elementGuidId>80a613e4-67cb-48bf-a75d-2bcfabdc6c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kecamatan_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kecamatan_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6cd4dea-8c4a-4e7e-b340-23d3e1767642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56ad8928-697f-4a56-9aba-7d2e63d61478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm uppercase ui-autocomplete-input</value>
      <webElementGuid>352644f6-7b9b-42b9-970d-afe2863da10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kecamatan_nama</value>
      <webElementGuid>0ce8bb90-f4ca-4e2b-82eb-5cd00ad92f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Kecamatan</value>
      <webElementGuid>d1931dc9-7b6a-4e2d-8ce1-648ace9526a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>3c4c7380-5f30-4e59-a57e-d4215e70b027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80c7a44b-5d4a-4cea-9e4f-46fb73d54b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;panel panel-default container-fluid&quot;]/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/input[@class=&quot;form-control input-sm uppercase ui-autocomplete-input&quot;]</value>
      <webElementGuid>eeb4b66c-77de-491c-a16b-c7383d9356e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kecamatan_nama']</value>
      <webElementGuid>6abe2e6f-e316-4e18-9eea-fd6b12a573f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[2]/div[6]/div[2]/div[3]/div/input[2]</value>
      <webElementGuid>68c2a7d3-9bed-49ab-9f92-bde7c6e2f5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>3c6e0ee5-f2b7-4ae4-941a-aa501cbedbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kecamatan_nama' and @placeholder = '🔍 Nama Kecamatan']</value>
      <webElementGuid>3139c049-5a40-4cd5-8c94-3fd6fd6579c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
