<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat Lahir_MPasientempat_lahir</name>
   <tag></tag>
   <elementGuidId>56b8975c-8c9c-4fd7-85d5-11d327b7ebe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;MPasien[tempat_lahir]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='MPasien[tempat_lahir]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1186ec6-7a58-400b-b528-70463a710270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>235e347a-def2-4b85-bc76-ba053228e1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm uppercase</value>
      <webElementGuid>593b46ea-e76d-4600-a013-88dcfb3d2ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[tempat_lahir]</value>
      <webElementGuid>f464c360-fd2d-4af2-b67a-0490e7426292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kota Lahir</value>
      <webElementGuid>48895d41-8d20-4dfe-8e8f-a8202178c122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>0d852489-5777-46ba-828d-bfacee79b67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/input[@class=&quot;form-control input-sm uppercase&quot;]</value>
      <webElementGuid>f2fb3186-320c-4676-83d5-04bed8f0a6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='MPasien[tempat_lahir]']</value>
      <webElementGuid>85db9e0f-f19b-4c54-bac9-9cf2fe9f4f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div/div[13]/div/input</value>
      <webElementGuid>15ba12ab-7eba-4706-838a-22ba9f4e204f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>0a4e3133-b87b-421e-acda-dc79642d5c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'MPasien[tempat_lahir]' and @placeholder = 'Kota Lahir']</value>
      <webElementGuid>02e8d0d6-e9a2-475a-a72b-aab785035625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
