<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buat Baru</name>
   <tag></tag>
   <elementGuidId>60805ab4-6797-449a-b481-a5fd4f82eef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_create</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b9290c3-c506-48c2-a940-14ccd1e21b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pasien/create</value>
      <webElementGuid>9b2b496f-e102-469b-bf48-db9b977371b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_create</value>
      <webElementGuid>b0348bab-3eea-4289-b0e7-cc7b9bcab6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92bc54cc-c286-443a-9e3a-d718b8a84e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>7c0700f2-f74d-4583-a9cc-1441ad52db47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat Baru</value>
      <webElementGuid>8fe059bf-ea4b-495a-b70d-c35f663968b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_create&quot;)</value>
      <webElementGuid>eb3ede58-cb2a-4376-a86d-555e67c7c339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_create']</value>
      <webElementGuid>5025ca15-9f28-4484-9c27-d91482e85bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/span[2]/a[2]</value>
      <webElementGuid>25b93ff9-2085-46b8-97d9-b6f51f439f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buat Baru')]</value>
      <webElementGuid>86ddbec7-b480-4ea5-bee0-cc669bb8ef69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur Tunda'])[1]/following::a[1]</value>
      <webElementGuid>fe72f9be-b24d-49c8-94f8-20367cb5ba52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pasien dan Kartu Keluarga'])[1]/following::a[2]</value>
      <webElementGuid>66ebe839-10b6-48bd-922c-2206f4fb45bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/preceding::a[1]</value>
      <webElementGuid>d9e1a77a-fc36-425c-b750-00db99b7c24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/preceding::a[1]</value>
      <webElementGuid>90cb3747-5ddc-4b3a-8ce3-254f2855dca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Baru']/parent::*</value>
      <webElementGuid>646e64dd-2781-455c-b8b5-dc85456817c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pasien/create')]</value>
      <webElementGuid>2e2949f6-0ce4-4d5e-b404-40433c460eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>03b53589-28c0-40b7-a8a3-c2e9837c5b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.epuskesmas.id/pasien/create' and @id = 'button_create' and @type = 'button' and (text() = 'Buat Baru' or . = 'Buat Baru')]</value>
      <webElementGuid>9d8afcb1-74cb-444a-832d-5a1fc0222da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
