<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BERASTAGI KABUPATEN KARO</name>
   <tag></tag>
   <elementGuidId>6e1afc4c-f217-4d17-b2b9-7455e5b579ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46f3c715-f3d6-4d82-95fb-aa4733688753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-28</value>
      <webElementGuid>6528e7d0-8a02-4547-98af-43c04fa41015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>624221bb-3449-485f-a096-9523fa7f04e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>2bbfd23e-88f4-43c7-a644-3535136d6d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BERASTAGI KABUPATEN KARO</value>
      <webElementGuid>99162f33-0560-473a-8688-2898c43312cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-28&quot;)</value>
      <webElementGuid>c38cb7a1-4975-4605-aa94-79bdc4ec6b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-28']</value>
      <webElementGuid>546770a5-59d3-4e8d-9aa5-028d74a0c6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-8']/li/div</value>
      <webElementGuid>b9d2593e-6006-48e7-bc5a-d48451add4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN KARO'])[1]/following::div[1]</value>
      <webElementGuid>a8ac0cdf-2a5a-400a-8d0a-737eea0c4cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[3]/following::div[5]</value>
      <webElementGuid>e545120a-8844-4626-a7d7-13d83461ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BERASTAGI'])[1]/preceding::div[2]</value>
      <webElementGuid>0da2eafe-f55e-436a-82a6-02b2cd7cd38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BERASTAGI']/parent::*</value>
      <webElementGuid>570f0bf7-bc95-43e6-8103-364f36699059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div</value>
      <webElementGuid>90afc11a-81cd-4d97-ac77-fd6858284fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-28' and (text() = 'BERASTAGI KABUPATEN KARO' or . = 'BERASTAGI KABUPATEN KARO')]</value>
      <webElementGuid>4daf92b6-b077-4808-8682-d0e75618d58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
