<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BANGUN PURBA KABUPATEN DELI SERDANG</name>
   <tag></tag>
   <elementGuidId>2dc893c8-6805-4bcd-a32b-4dc48c7f3f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>454e6516-8a48-4ecc-9845-eab907038907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-28</value>
      <webElementGuid>eee221a1-76aa-4028-ba49-63970302b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fb5cbdc1-6a0e-4fcf-a17e-02768e54fa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>9eee07ed-4e07-4de4-93d6-d256f63c8166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BANGUN PURBA KABUPATEN DELI SERDANG</value>
      <webElementGuid>3963e9ac-c652-4587-a806-ea42e00368d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-28&quot;)</value>
      <webElementGuid>44d0812f-dffa-4f89-ad75-3aec5d0fc7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-28']</value>
      <webElementGuid>7b3862a8-832b-40a2-a331-9d08f74cb6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-8']/li/div</value>
      <webElementGuid>dd138ad2-925b-4cb6-a84a-7ee2fa185b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN DELI SERDANG'])[1]/following::div[1]</value>
      <webElementGuid>6df1861f-0e55-47bd-8cd3-453a49ca70c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[3]/following::div[5]</value>
      <webElementGuid>57bb0b20-f489-4f1d-86c0-406d3dccd11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANGUN PURBA'])[1]/preceding::div[2]</value>
      <webElementGuid>25394330-d8e8-4ad5-b669-83d66f40eeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BANGUN PURBA']/parent::*</value>
      <webElementGuid>2bafda33-78eb-4410-8383-7e685a2ca36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div</value>
      <webElementGuid>5cae9802-049c-4829-91f1-78cb53af9a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-28' and (text() = 'BANGUN PURBA KABUPATEN DELI SERDANG' or . = 'BANGUN PURBA KABUPATEN DELI SERDANG')]</value>
      <webElementGuid>e56492db-06ea-4127-a250-05161ed95ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
