<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KABUPATEN KARO SUMATERA UTARA</name>
   <tag></tag>
   <elementGuidId>e8cc8c36-344d-4f0e-ad1d-b58f941ba212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-27']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-27</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ae836a7-aeeb-43dd-8728-43c346ae6db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-27</value>
      <webElementGuid>eb1e2765-4310-447f-a5b5-ed4faf56179e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4b543225-a232-45a7-91d7-483d4f27f1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>259c0d77-08f4-43f6-a4a0-07ddb68e712e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KABUPATEN KARO SUMATERA UTARA</value>
      <webElementGuid>cd53c4dd-eb7e-45a8-8aa6-a9135cf07238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-27&quot;)</value>
      <webElementGuid>21eaf41c-7d18-4b9a-9d11-53af139a4d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-27']</value>
      <webElementGuid>72991dab-40f6-4697-8489-a40d597dcaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-7']/li/div</value>
      <webElementGuid>58f6b71b-118d-4be2-9b1a-16fa9ca3bfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[2]/following::div[1]</value>
      <webElementGuid>7d9a1d93-736e-4df2-b3dd-ff343d9ee5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[1]/following::div[4]</value>
      <webElementGuid>b5ff1eaf-288f-4af3-8938-dd878e91c3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN KARO'])[1]/preceding::div[3]</value>
      <webElementGuid>fce1a50a-c87f-4bff-bac6-1b4f70af5fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KABUPATEN KARO']/parent::*</value>
      <webElementGuid>081d5dc6-3d89-485b-8c33-88bf76fd3138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div</value>
      <webElementGuid>da1807e8-ec6d-4703-8bad-2977ef307f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-27' and (text() = 'KABUPATEN KARO SUMATERA UTARA' or . = 'KABUPATEN KARO SUMATERA UTARA')]</value>
      <webElementGuid>71fc96b8-a82f-4e21-9474-780d018b7e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
