<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GREAHAN BANGUN PURBA</name>
   <tag></tag>
   <elementGuidId>b560989a-1b21-499d-91ab-1cb1fbf9c9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de63d98a-a728-4093-b147-36e515dc22a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-29</value>
      <webElementGuid>14d7429a-876a-4c1f-87d2-d56f336154d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e5139e17-0798-4298-becf-d10293873643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>9fdefafc-4d14-40a2-aa77-c720132e55ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GREAHAN BANGUN PURBA</value>
      <webElementGuid>a7c1b27d-d15e-458c-a243-e116317bce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-29&quot;)</value>
      <webElementGuid>6d9b7ca1-be67-4bb7-ae67-606d724c2095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-29']</value>
      <webElementGuid>6629b60f-7f00-42c1-ba36-505508963ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-9']/li/div</value>
      <webElementGuid>f980004e-72d3-43b5-9b3a-9e252e78d80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANGUN PURBA'])[1]/following::div[1]</value>
      <webElementGuid>60a1bec4-bafa-4e85-a7c7-bc4923da8e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN DELI SERDANG'])[2]/following::div[4]</value>
      <webElementGuid>d781ae37-7c7a-4b61-8927-88e32146e9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No search results.'])[1]/preceding::div[1]</value>
      <webElementGuid>785ac23b-405a-4278-b587-f4fe84d63c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GREAHAN']/parent::*</value>
      <webElementGuid>12d400fa-bc9d-4c60-aec2-78897c51c3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[9]/li/div</value>
      <webElementGuid>ddbc6b1d-16f7-475c-8001-aaa201b9fad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-29' and (text() = 'GREAHAN BANGUN PURBA' or . = 'GREAHAN BANGUN PURBA')]</value>
      <webElementGuid>e933a39d-75bd-4042-a7ef-6070a21e952a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
