<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MABAR BANGUN PURBA</name>
   <tag></tag>
   <elementGuidId>8c8e225f-8645-4e46-b4d5-dea5f87e81a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-29']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5370f7f-382f-4f92-b9f5-fdd510920665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-29</value>
      <webElementGuid>9bfc5bae-393c-40c9-b051-726e2973e3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>159ddf00-f511-45a4-92a6-890ae1eff495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>a80850d5-f79a-4827-bd23-9fa674a17f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MABAR BANGUN PURBA</value>
      <webElementGuid>d9c35f68-a01b-4480-94c2-346ffc1f0e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-29&quot;)</value>
      <webElementGuid>6a11b77a-d444-49e2-81cb-f20097ccb4e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-29']</value>
      <webElementGuid>98cab912-0815-4d29-bab9-035faafa6030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-9']/li/div</value>
      <webElementGuid>0d3097c9-eb7a-4598-9318-e4cff94f67a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANGUN PURBA'])[1]/following::div[1]</value>
      <webElementGuid>eda1bd27-e8de-4b6d-be48-d5c6966026ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KABUPATEN DELI SERDANG'])[2]/following::div[4]</value>
      <webElementGuid>be19f33a-8b58-4b72-81a5-58341adc8173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MABAR'])[1]/preceding::div[2]</value>
      <webElementGuid>14f095c3-2047-4fa7-8848-80004eb011a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MABAR']/parent::*</value>
      <webElementGuid>cd799544-8b7e-49b5-b95b-c076dbb482d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[9]/li/div</value>
      <webElementGuid>e34015b9-ac6f-4bca-9a01-86191615311b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-29' and (text() = 'MABAR BANGUN PURBA' or . = 'MABAR BANGUN PURBA')]</value>
      <webElementGuid>552a9be0-7571-472b-967f-9ba280dd0584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
