<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih -                           _73a496</name>
   <tag></tag>
   <elementGuidId>6f4351a2-376f-490d-a558-933790e9c93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='MPasien[warganegara]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;MPasien[warganegara]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>63f6e79d-d2c5-4638-af80-422181c088a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm warganegara</value>
      <webElementGuid>46b7b29b-25bb-45dd-8647-08ffbbc7fc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[warganegara]</value>
      <webElementGuid>a0a94ce8-25ad-431a-809d-33ccbb13b9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ba24901c-d154-4863-b9b7-fef7ed4b158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    </value>
      <webElementGuid>28ca0675-e696-4ea4-a9ef-7568bbe919a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_creates&quot;)/div[@class=&quot;panel-body row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/select[@class=&quot;form-control input-sm warganegara&quot;]</value>
      <webElementGuid>e2c0adfa-7368-48df-aef1-ab3155e956bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='MPasien[warganegara]']</value>
      <webElementGuid>aa829b53-1644-4fcd-b64a-b071d74bc8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div[3]/div[10]/div/select</value>
      <webElementGuid>6c0614f7-4b6c-467a-887b-48abf12f435b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::select[1]</value>
      <webElementGuid>b3da7f8c-2e9b-4a20-a6f1-481ef9a330b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Paspor'])[1]/preceding::select[1]</value>
      <webElementGuid>4b615e78-327b-402d-b2b1-ac4b0a753364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Ayah/KK'])[1]/preceding::select[1]</value>
      <webElementGuid>66bbf198-0fb9-4fe9-9cdc-a72b24634264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>d95d4ab5-0f5e-47fc-8bbd-379b833fab07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'MPasien[warganegara]' and (text() = '
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    ' or . = '
                            - Pilih -
                                                                                                INDONESIA
                                                                    ASING
                                                                                    ')]</value>
      <webElementGuid>fb40d833-8d61-4dee-8f21-906d0433adf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
