<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ePuskesmas</name>
   <tag></tag>
   <elementGuidId>ee837715-a3ad-4a04-8a29-5e9b5a966e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa866b07-ef89-4475-915c-10f37341cd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ePuskesmas</value>
      <webElementGuid>ae935263-cd90-4892-b1da-e27356ade015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/nav[@class=&quot;navbar-inner fixed-bottom navbar-light&quot;]/ul[@class=&quot;col-md-4 col-sm-4 col-xs-4 bg-primary-2 green&quot;]/li[1]/ul[@class=&quot;drop-menu menu-4&quot;]/li[@class=&quot;green&quot;]/a[1]/span[1]</value>
      <webElementGuid>9e4bc75a-d8fe-45fb-9791-c08074544442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      <webElementGuid>3187d4dc-580d-47f9-9f66-49e3585dd49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puskesmas . Dinas Kesehatan'])[1]/following::span[1]</value>
      <webElementGuid>75a2fe30-8bea-47a1-87b5-63d4b6f2abf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ePosyandu'])[1]/preceding::span[1]</value>
      <webElementGuid>86b8c532-d486-4cca-b821-949797a367fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eClinic'])[1]/preceding::span[2]</value>
      <webElementGuid>0dea0a6f-5241-4791-9ff5-7791fa4d5e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>1967d6f2-ad84-4562-acf2-bac20a7ee6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ePuskesmas' or . = 'ePuskesmas')]</value>
      <webElementGuid>36d878ae-3e2f-4171-87cc-bd9e6247e391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
