<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ePuskesmas</name>
   <tag></tag>
   <elementGuidId>e143a7f1-238e-48b8-aa18-0b4e44172e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f60a2c7-2832-4c47-a35c-5ccc17a678d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ePuskesmas</value>
      <webElementGuid>d21a4687-48ea-4946-a7e1-9fc16a79f8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/nav[@class=&quot;navbar-inner fixed-bottom navbar-light&quot;]/ul[@class=&quot;col-md-4 col-sm-4 col-xs-4 bg-primary-2 green&quot;]/li[1]/ul[@class=&quot;drop-menu menu-4&quot;]/li[@class=&quot;green&quot;]/a[1]/span[1]</value>
      <webElementGuid>d3e4a596-3d2e-4281-93e7-5080ac4ba033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      <webElementGuid>bd8238e5-ec61-4908-a83e-31dd78813f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puskesmas . Dinas Kesehatan'])[1]/following::span[1]</value>
      <webElementGuid>01303e43-a577-482e-b69a-27feba1e8928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ePosyandu'])[1]/preceding::span[1]</value>
      <webElementGuid>65ecb924-7859-4768-afe6-cbb12231d399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eClinic'])[1]/preceding::span[2]</value>
      <webElementGuid>b9e4f74b-dd19-4da1-9a0c-cdd863bfa85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>12b20f11-08a4-4eba-982b-f35f46b5c4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ePuskesmas' or . = 'ePuskesmas')]</value>
      <webElementGuid>a8391787-b1c0-493c-8585-fe6958d09a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
