<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pasien  KK</name>
   <tag></tag>
   <elementGuidId>63aba543-d55c-4062-83f7-792ad2b71d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_pendaftaran_pasien</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pendaftaran_pasien']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb791f0a-53db-4eb8-bf51-f1e0bf535534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pendaftaran_pasien</value>
      <webElementGuid>ab2542c1-6437-4b5d-8866-8eba0f4e162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pasien?broadcastNotif=1</value>
      <webElementGuid>ad9e713d-e588-4136-9c46-9842a05a33f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pasien &amp; KK</value>
      <webElementGuid>6c8bb452-7741-4d62-ae1c-48a3ed717273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pendaftaran_pasien&quot;)</value>
      <webElementGuid>adbfce21-d321-44a6-8f40-0525013841f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pendaftaran_pasien']</value>
      <webElementGuid>439a20b9-bb41-4c73-bd16-2f04fa71e7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul/li/ul/li/a</value>
      <webElementGuid>e6bd94eb-7cf5-437d-81b3-c618e1d7396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pasien &amp; KK')]</value>
      <webElementGuid>b99ff1fd-34db-4414-9aae-67d5e4826cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>4eb8ab8a-5ecc-49de-8edf-96afececfcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran Pasien'])[1]/preceding::a[1]</value>
      <webElementGuid>0bc46c28-b3a6-4046-96fe-4e8bd1d7e2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::a[2]</value>
      <webElementGuid>7f82f584-c1a6-4b75-8d19-349fbefc63b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pasien &amp; KK']/parent::*</value>
      <webElementGuid>48748fff-ac8a-48af-b5b6-1a4f7cab86a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pasien?broadcastNotif=1')]</value>
      <webElementGuid>2434dedf-b205-4483-ae7d-03400916e2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>bd3d5df6-1a7b-4baf-9a2d-0320c83d70c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_pendaftaran_pasien' and @href = 'https://demo.epuskesmas.id/pasien?broadcastNotif=1' and (text() = 'Pasien &amp; KK' or . = 'Pasien &amp; KK')]</value>
      <webElementGuid>bd987643-0d51-4b69-a30a-a9590d83fff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
