<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Diverifikasi (lengkap)_MPasienverified_by</name>
   <tag></tag>
   <elementGuidId>8d6f4337-fa5c-4635-9f35-0d2e84a930ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checked_verifikasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checked_verifikasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b46450b9-bae8-40d0-b99c-52d08f5b6557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checked_verifikasi</value>
      <webElementGuid>66d8ec4a-281e-418f-803d-8eab24bd4ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73aeb20e-5f15-4ea8-a6f2-8fc80cc4ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MPasien[verified_by]</value>
      <webElementGuid>225fe628-8521-4d22-9612-74e58f4fdfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>darel</value>
      <webElementGuid>293b6c45-a757-4e59-82e8-9aea9698a637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checked_verifikasi&quot;)</value>
      <webElementGuid>2c05db8a-748e-42b4-a8c2-b068d64f5c80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checked_verifikasi']</value>
      <webElementGuid>d7a554c6-e1e5-43b1-ab2f-e3c95a682f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_creates']/div/div/div/div/label/input</value>
      <webElementGuid>5c5ca108-efba-4e5e-8645-53a7ee396adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>5a7e4e2b-0fc7-4394-afcf-9ee0df961651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checked_verifikasi' and @type = 'checkbox' and @name = 'MPasien[verified_by]']</value>
      <webElementGuid>484f63ac-3196-44cc-96fc-3c67c0b27c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
