<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_A05 - Other bacterial foodborne intoxic_cb08f5</name>
   <tag></tag>
   <elementGuidId>bd32262b-f1a0-4fc0-a790-d80114e839eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de82bb09-9f87-4a19-bd1a-1aec5194f98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-12</value>
      <webElementGuid>48fe6f80-925b-4865-9a44-6da7e30de8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b30fa15f-85b7-48e7-96b0-47df17612955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>948bc961-2f20-4120-8551-f714d31fea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A05 - Other bacterial foodborne intoxications, not elsewhere classified</value>
      <webElementGuid>8a075480-74eb-4800-94ec-a51843e810da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-12&quot;)</value>
      <webElementGuid>e69b5ac6-3ae8-4876-84a9-c75b7d6e5245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-12']</value>
      <webElementGuid>ea9917f7-f9c2-4c67-ba25-7ec2ccd086c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-10']/li[2]/div</value>
      <webElementGuid>18095b05-9af1-4614-b752-8816c9c98b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A04.2 - Enteroinvasive Escherichia coli infection'])[1]/following::div[1]</value>
      <webElementGuid>a0aeb292-dbcc-441f-9d9b-93f61d6034a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I GUSTI NGURAH ARTA PASCA SUPUTRA'])[1]/following::div[2]</value>
      <webElementGuid>f30a2f19-c700-460e-b342-b6e27a2494ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A06 - Amoebiasis'])[1]/preceding::div[1]</value>
      <webElementGuid>6a98f349-c28f-4136-bf2f-ee1aa1a54c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A06.1 - Chronic intestinal amoebiasis'])[1]/preceding::div[2]</value>
      <webElementGuid>d5226444-6858-48ec-9f89-4342d4d94eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A05 - Other bacterial foodborne intoxications, not elsewhere classified']/parent::*</value>
      <webElementGuid>aa747212-53c7-40cb-b9fe-b35164f2a7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/div</value>
      <webElementGuid>a879ded2-0829-4b75-ae3b-3aaf4bbca3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-12' and (text() = 'A05 - Other bacterial foodborne intoxications, not elsewhere classified' or . = 'A05 - Other bacterial foodborne intoxications, not elsewhere classified')]</value>
      <webElementGuid>f8bf62ae-2d40-4503-b32d-395b3fa387a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
