<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I GUSTI NGURAH ARTA PASCA SUPUTRA (Dokt_f68b5f</name>
   <tag></tag>
   <elementGuidId>dae8c951-1e6a-4452-814a-5fb8a51ee162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf0215b4-83a4-4691-99b0-4c2c1c00d81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-3</value>
      <webElementGuid>dec80e99-4b17-48ae-ad98-8f783ad3dfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ff51c827-ee66-45c7-845c-badf752d98d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>c15c1032-2536-47ec-a462-78ccaf59bf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I GUSTI NGURAH ARTA PASCA SUPUTRA (Dokter Umum)</value>
      <webElementGuid>e84fc35b-be32-46fe-a042-9e10c58c3ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-3&quot;)</value>
      <webElementGuid>af5dc61d-fb34-43ab-8bd1-e02b8cb98d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']</value>
      <webElementGuid>0cebf5d5-07b3-43e6-bfa3-2e9d946ba487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[2]/div</value>
      <webElementGuid>9277b628-5542-487c-8813-4b9444b39825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NASYRATUL ILMI (Bidan)'])[1]/following::div[1]</value>
      <webElementGuid>a68bfffc-2fd3-4715-8e06-031abf3c9906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-3', '&quot;', ')')])[1]/following::div[2]</value>
      <webElementGuid>ae550b9a-7b1b-4af8-af47-fdeddea91ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDA AYU SRI ASTINI (Perawat Gigi)'])[1]/preceding::div[1]</value>
      <webElementGuid>cf3b118b-c101-4d34-801b-520a2176c258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI LUH PUTU SHINTA DEVI ARYASTINI GUNAWAN (Perawat)'])[1]/preceding::div[2]</value>
      <webElementGuid>29de20ef-41a3-43df-9263-a552d74e76cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I GUSTI NGURAH ARTA PASCA SUPUTRA (Dokter Umum)']/parent::*</value>
      <webElementGuid>0bfa3f09-8231-435f-8b65-097124a0be0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>02edb266-67c6-4740-be7c-5b76a23d483c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-3' and (text() = 'I GUSTI NGURAH ARTA PASCA SUPUTRA (Dokter Umum)' or . = 'I GUSTI NGURAH ARTA PASCA SUPUTRA (Dokter Umum)')]</value>
      <webElementGuid>0692355e-d6f7-4627-8920-9b2d0c7368c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
