<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_diagnosa_id</name>
   <tag></tag>
   <elementGuidId>5484de47-582e-42a2-b5e7-fcbbcd98fc30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='diagnosa_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;diagnosa_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4315b40-1e75-49c5-9ec1-c32c33a0d023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>735491dd-cc5d-4bf2-84ef-b2ca81bf3653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>diagnosa_id</value>
      <webElementGuid>84fad3d8-edc3-43bf-b7cf-6b11d2e95441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>autocompleteDiagnosa(this);</value>
      <webElementGuid>3e477327-27ba-4db3-beb9-b4e646193254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>86192b6c-4f3c-49b0-85ad-f5beadff052a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>diagnosa_id</value>
      <webElementGuid>0ac0479e-f0e6-4154-85eb-76b3ac26c019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Cari ICD-X</value>
      <webElementGuid>bec42397-3926-4cea-9acc-a901be64c43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>191</value>
      <webElementGuid>b4acb744-059e-4c08-bedf-d6e180db0047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bpjs</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>431121e0-f6c4-4615-945b-5d734decf2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b749b7e2-2b7f-40cd-b783-37231a5fb298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_1&quot;)/td[3]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>66e324bd-21b2-4450-b25c-c6838c1393ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='diagnosa_id']</value>
      <webElementGuid>6ed6ec0c-3c9f-4d01-a4af-54de08930532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[3]/input[2]</value>
      <webElementGuid>f7f613fe-0c8b-46b2-afe2-fcba8eba8d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input[2]</value>
      <webElementGuid>c575d06a-4afc-42d6-a371-819f0aa52e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'diagnosa_id' and @placeholder = '🔍 Cari ICD-X']</value>
      <webElementGuid>d8fbe3b4-88f2-4ab8-9626-ae18038c83ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
