<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anamnesa</name>
   <tag></tag>
   <elementGuidId>7cdf9c8a-bb08-465b-94af-eb2943c5b574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_anamnesa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_anamnesa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01e8b345-d81c-485d-8583-e4122a59aa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/anamnesa/create/9616?from='pelayanan'&amp;action='edit'</value>
      <webElementGuid>ad4a1ce8-688f-432f-8f1d-9d26981303df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_anamnesa</value>
      <webElementGuid>b1a15b8b-bfef-4c29-b84e-b8dde086031a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>b6ff2803-6705-442d-b03e-44b27002491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anamnesa</value>
      <webElementGuid>5ce3a4d3-c3d8-4dba-9ba7-7975c2665e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_anamnesa&quot;)</value>
      <webElementGuid>2b114d19-95c4-470a-b757-4dbcbc5ee008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_anamnesa']</value>
      <webElementGuid>a9b54602-bc7e-4efa-8b27-de9bbecd7d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[2]/div[2]/div/a[3]</value>
      <webElementGuid>f06e8e50-7967-49c2-a173-b0d4349fb8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anamnesa')]</value>
      <webElementGuid>9cf98471-b124-479d-8344-92b677f63be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[1]/following::a[1]</value>
      <webElementGuid>14d50c87-77a2-4dc6-be7b-a18293d86774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[2]/following::a[2]</value>
      <webElementGuid>56ed2606-740a-43a2-ba17-ee38cb0ccd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosa'])[2]/preceding::a[1]</value>
      <webElementGuid>39eac55a-8eb3-4076-8e90-c2b3580e797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[2]/preceding::a[2]</value>
      <webElementGuid>599b8482-99dc-4b8a-b7ba-a0ffd8996e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anamnesa']/parent::*</value>
      <webElementGuid>2eb89d48-5dd6-4c49-bffe-b3c89b7583aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://demo.epuskesmas.id/anamnesa/create/9616?from='pelayanan'&amp;action='edit'&quot;)]</value>
      <webElementGuid>e4f1122d-afee-418c-8f54-b3dedc002010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>dbfdd87c-24f9-48ab-bad7-68f3aca3b797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;https://demo.epuskesmas.id/anamnesa/create/9616?from=&quot; , &quot;'&quot; , &quot;pelayanan&quot; , &quot;'&quot; , &quot;&amp;action=&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot;) and @id = 'button_anamnesa' and (text() = 'Anamnesa' or . = 'Anamnesa')]</value>
      <webElementGuid>b058c4c2-c3e3-4dcd-988f-caa3f4ca02f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
