<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Diagnosa</name>
   <tag></tag>
   <elementGuidId>1706ff5b-a895-4230-8823-91d50e9eb755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_diagnosa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_diagnosa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>734c396d-b4fd-4f34-8e04-8cec4e7621a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/diagnosa/create/9652?from='pelayanan'&amp;action='edit'</value>
      <webElementGuid>c6023306-7d4f-4664-9a40-7ec6f8395ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_diagnosa</value>
      <webElementGuid>d9929545-1ddb-4cf4-9e8f-079e2f8e5b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>88ddc215-9797-4116-b867-90db25115649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diagnosa</value>
      <webElementGuid>bc54c995-8a9d-4b53-81c6-e7020dde1cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_diagnosa&quot;)</value>
      <webElementGuid>b6b9f013-8780-49bd-9a8e-ba6fa359c6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_diagnosa']</value>
      <webElementGuid>039f1cd1-8744-46bc-92a9-2f03773d008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[2]/div[2]/div/a[4]</value>
      <webElementGuid>7d0fce3e-a848-4e56-8a40-b0db8279aa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Diagnosa')])[2]</value>
      <webElementGuid>905ccd5a-472f-46c0-898e-2efececc0bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anamnesa'])[1]/following::a[1]</value>
      <webElementGuid>a5910ee5-b932-4843-8e97-a4fbf8437ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[1]/following::a[2]</value>
      <webElementGuid>f5ea17b4-4887-4f4d-aea2-3e21908dda4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[2]/preceding::a[1]</value>
      <webElementGuid>82ae44c2-b5eb-4d9b-8e78-5bf350754ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alkes'])[2]/preceding::a[2]</value>
      <webElementGuid>8cd228dc-0ad2-4bde-a10b-6378a212a146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://demo.epuskesmas.id/diagnosa/create/9652?from='pelayanan'&amp;action='edit'&quot;)]</value>
      <webElementGuid>2259eae8-832d-4c94-beee-70f01d8dc25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>6acaf60f-e43c-418a-874f-13eaeb554341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;https://demo.epuskesmas.id/diagnosa/create/9652?from=&quot; , &quot;'&quot; , &quot;pelayanan&quot; , &quot;'&quot; , &quot;&amp;action=&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot;) and @id = 'button_diagnosa' and (text() = 'Diagnosa' or . = 'Diagnosa')]</value>
      <webElementGuid>16bea848-8694-4a45-bb5b-9741ebb5aedd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
