<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DR.HILMAI PICAL MUSLIM (Dokter Umum)</name>
   <tag></tag>
   <elementGuidId>80ceca7d-18d5-4486-876e-d07017d595b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47d91664-6149-42ff-8fab-298950c8e9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-6</value>
      <webElementGuid>1e9cb6a0-5752-424a-9f20-ad79ca0ad9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9eb2b070-c7e4-4577-8d41-9fed56f9604b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>2d91df54-2e5b-4846-a0af-d01f79116252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DR.HILMAI PICAL MUSLIM (Dokter Umum)</value>
      <webElementGuid>c12ed178-3222-40b7-bb12-eae6088fcb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)</value>
      <webElementGuid>cb872d03-ba4c-4d5b-a8cf-9a1a7a9c8283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-6']</value>
      <webElementGuid>23b293f3-47ad-4a2e-81d0-477ba0c4292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li/div</value>
      <webElementGuid>2839094c-f3e7-4413-9dc9-40b39ca7037c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[1]</value>
      <webElementGuid>38b46718-0cab-4bdc-a6bc-a572485a3c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/following::div[1]</value>
      <webElementGuid>8a95d226-6d03-4d3a-86af-3a82ad816024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR RAFLES (Dokter Umum)'])[1]/preceding::div[1]</value>
      <webElementGuid>bf71fe1a-d6e7-4d1b-bc1a-5405866e6a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dr.Rizki Amalia (Dokter Umum)'])[1]/preceding::div[2]</value>
      <webElementGuid>f86f83d3-8b83-4339-9941-7b2d47c26db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DR.HILMAI PICAL MUSLIM (Dokter Umum)']/parent::*</value>
      <webElementGuid>c5bc9564-ae05-49b4-97a7-0b6f58a960b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li/div</value>
      <webElementGuid>0d287f89-61ca-4fc3-892c-95f72a0e68c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-6' and (text() = 'DR.HILMAI PICAL MUSLIM (Dokter Umum)' or . = 'DR.HILMAI PICAL MUSLIM (Dokter Umum)')]</value>
      <webElementGuid>e92303fd-a9a5-4eb7-9aa8-b904d0c8f98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
