<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ray S.Farm (Apoteker)</name>
   <tag></tag>
   <elementGuidId>370038d7-b5d1-4acf-b5ac-a2345d5683b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0efec941-3c07-43d4-92c7-7a31a99d5893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-6</value>
      <webElementGuid>f62c969c-76a0-41cf-bc91-b9b87278de38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3fe51815-79f7-4429-9496-abcff3bfdd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>087e7db7-466f-4629-8286-f30daba65fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ray S.Farm (Apoteker)</value>
      <webElementGuid>8521ceed-eb5c-479d-9988-2d6afa2e67ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)</value>
      <webElementGuid>df70c122-b113-4394-a765-ee96cc48ca8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-6']</value>
      <webElementGuid>736eacc5-ee0d-4848-b046-9899a213c098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li/div</value>
      <webElementGuid>761c8383-3ad8-4c36-a4a1-af0853684797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[1]</value>
      <webElementGuid>66f1632e-a061-49de-b4f3-4cc340cb95e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[1]/following::div[1]</value>
      <webElementGuid>ff36aeec-78fa-4eaa-87b3-fb7bfeea3d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yandri (Staf Non Medis)'])[1]/preceding::div[1]</value>
      <webElementGuid>70521011-dd31-4c4d-a1d3-9609c018e4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR. YUDISTIRA (Dokter Gigi)'])[1]/preceding::div[2]</value>
      <webElementGuid>4cf55be5-3c74-4c73-979d-43a590a2daa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ray S.Farm (Apoteker)']/parent::*</value>
      <webElementGuid>7339b525-3e87-4165-9fae-c7dfe2bc348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li/div</value>
      <webElementGuid>85926ff0-584b-4678-b0d5-8d1418e49049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-6' and (text() = 'Ray S.Farm (Apoteker)' or . = 'Ray S.Farm (Apoteker)')]</value>
      <webElementGuid>905eb279-132d-42d8-bc8e-bb2d43aaf673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
