<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PeriksaFisikdetak_nadi</name>
   <tag></tag>
   <elementGuidId>6dca5c0c-8760-4fdd-b422-c77678f9af1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='PeriksaFisik[detak_nadi]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;PeriksaFisik[detak_nadi]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27d81507-978b-4615-9978-bda9b05b7331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fb7192d7-93b0-42f1-8913-5aa56b212487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>84dfab02-f741-4ac6-b9e4-74fc90a50c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ba2590dc-98e7-4ccc-8aca-5d62e638fe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3a941ac-74d4-4913-a91e-528741388e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>d826e611-1b2b-4769-ab6e-9afb315d67c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriksaFisik[detak_nadi]</value>
      <webElementGuid>7a78f7cf-eff4-4d0c-b652-eef60de45702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49f007a0-702f-44af-b5c9-c7cb96cfbe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>42792227-9cf4-48cf-8f79-c5c08cdf000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box box-bordered&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>3f945c88-cde2-44d9-befb-562d1a8a1dfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='PeriksaFisik[detak_nadi]']</value>
      <webElementGuid>37c394d3-215f-45cd-9a49-9ca27b979f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>305bada2-24a2-4ff1-af95-c7d4df433c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>4f6e0879-f87f-4ff2-9301-9a7cc79c8398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'PeriksaFisik[detak_nadi]' and @placeholder = '0']</value>
      <webElementGuid>ebc23650-f279-4119-88ec-2391ad5c5b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
