<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Darurat_PeriksaFisiktriage</name>
   <tag></tag>
   <elementGuidId>78aada7a-0ce6-4cb0-941d-9f3d7df300de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='PeriksaFisik[triage]'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8989ac13-28d0-48dd-a242-9ece098dd183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8ffe9d98-81ed-4c82-acb2-62d568ba7ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriksaFisik[triage]</value>
      <webElementGuid>d733c258-19b1-45e0-973d-0e7ede886f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TIDAK GAWAT DARURAT</value>
      <webElementGuid>def2b04e-d608-431f-9bac-11e954317609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box box-bordered&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/div[@class=&quot;input-group&quot;]/label[@class=&quot;radio-inline&quot;]/input[1]</value>
      <webElementGuid>522909aa-c924-4b8f-a4aa-4b1db2680d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='PeriksaFisik[triage]'])[3]</value>
      <webElementGuid>a06ce442-6915-477c-8f83-fe260f42bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[2]/div/div[2]/div[2]/div[7]/div/div[2]/label/input</value>
      <webElementGuid>1e1aa0fe-3029-45ac-a7e8-c3bc9d2af71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>77367051-b96d-4d74-a836-7b288f08eaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'PeriksaFisik[triage]']</value>
      <webElementGuid>57a067cd-34a0-46f8-a7b2-f1d98e743b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
