<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dokter_nama</name>
   <tag></tag>
   <elementGuidId>bd5bdf7c-79da-4860-a08c-103f4aeb9801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dokter_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dokter_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f1299fa-2344-4830-bc2d-f026ee07c880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6d83341-7a9a-4e96-9dda-0864c22f9ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ui-autocomplete-input</value>
      <webElementGuid>23fa50b6-2c2a-48f2-8936-24d27f169a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dokter_nama</value>
      <webElementGuid>7ca33f20-7b9a-458a-95cd-eb8b335f56ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Dokter / Bidan / Perawat</value>
      <webElementGuid>4e8cbf90-6cc3-493c-b1b8-2796097a08b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>bb65f87d-693a-4f6c-bca5-b0ed800026e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8ed785a-bc29-4391-aff8-ad162e03da2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;form-group col-sm-6&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/input[@class=&quot;form-control input-sm ui-autocomplete-input&quot;]</value>
      <webElementGuid>8159f09a-edb7-44b9-85e9-07248a7a44cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dokter_nama']</value>
      <webElementGuid>31278c52-4ee5-4d65-bef6-80267306d555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div/div/div[2]/div/div/input[3]</value>
      <webElementGuid>ae94a1c9-4852-4a50-bb8a-6f0847887903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[3]</value>
      <webElementGuid>fc0d3452-2360-42c4-abe6-5c6b17a91b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dokter_nama' and @placeholder = '🔍 Nama Dokter / Bidan / Perawat']</value>
      <webElementGuid>d970600c-24b0-43bd-94ab-a573ef9191e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
