<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tgl. Rencana Kontrol_Pelayanantanggal_69c6dd</name>
   <tag></tag>
   <elementGuidId>b699abb8-09b6-419c-9d67-825c1a57f804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Pelayanan[tanggal_kontrol]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Pelayanan[tanggal_kontrol]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e2b78bc-0a36-4edd-ae9f-5b05d00dfb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa90ea25-e236-4b8d-98dd-cd763e0ba14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm </value>
      <webElementGuid>48a07d1e-5159-41a8-8057-f24ba277625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pelayanan[tanggal_kontrol]</value>
      <webElementGuid>3e0bd2a7-4606-49d8-bcbc-4e2a5e67d517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd-mm-yyyy</value>
      <webElementGuid>63ee1a15-5185-4005-96e0-88fc2e5df891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_pasienpulang&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;input-group date-next&quot;]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>72c504f0-657b-4eae-bbc6-bd1c336f5954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Pelayanan[tanggal_kontrol]']</value>
      <webElementGuid>af0cf2a6-fc98-4642-953f-c0ad24d8a6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_pasienpulang']/div[5]/div/div/input</value>
      <webElementGuid>fadd252e-e8ac-446e-b78a-e4148c97853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>bf4c4b00-f9e7-40e4-ae79-f5bd8ac2ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Pelayanan[tanggal_kontrol]' and @placeholder = 'dd-mm-yyyy']</value>
      <webElementGuid>a17df269-b372-49d3-bbac-e4f2f393441b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
