<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Berdiri                             _edde5f</name>
   <tag></tag>
   <elementGuidId>c4b7055b-e1aa-4b66-9ed4-9844f08a5542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cara_ukur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cara_ukur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>565b95e9-665b-4843-9556-4f112cdb7110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>0ad3be6d-2852-4ef5-9fe6-05d7c8ce7ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriksaFisik[cara_ukur]</value>
      <webElementGuid>5312bb11-d7cc-4314-bb81-1e1625e656bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cara_ukur</value>
      <webElementGuid>f342c8de-7e30-4eb6-be02-79d9723cd5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>hitungImt();</value>
      <webElementGuid>df893653-6f8e-4ef1-bc58-fb9b91f651cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Berdiri
                                                    Telentang
                                                </value>
      <webElementGuid>491333c4-05ee-481b-82f6-b33b91740afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cara_ukur&quot;)</value>
      <webElementGuid>1812261a-3dd3-46c3-b168-0170d00eb377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cara_ukur']</value>
      <webElementGuid>340743a2-9450-4977-929d-d9ac12f1cdcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[2]/div/div[2]/div/div[5]/div/select</value>
      <webElementGuid>bec5119c-7b28-4687-a223-fbc5bea306f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>2055969c-98f3-4bf4-84e8-ae048a801260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>34037a6b-fe80-4251-9baa-100119432229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>8545e7bc-7907-4971-bceb-79031c112901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PeriksaFisik[cara_ukur]' and @id = 'cara_ukur' and (text() = '
                                                    Berdiri
                                                    Telentang
                                                ' or . = '
                                                    Berdiri
                                                    Telentang
                                                ')]</value>
      <webElementGuid>c280ea18-c33d-48b8-a69c-3c65a8b3400e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
