<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_COMPOS MENTIS                       _312887</name>
   <tag></tag>
   <elementGuidId>5f7ef8c3-edfb-458e-b2cc-6da0ddad8908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='PeriksaFisik[kesadaran]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;PeriksaFisik[kesadaran]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>759851b1-7054-4a41-973f-7bb5634293ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>fe5ab4b2-a867-47a9-852f-94ad1a14bda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriksaFisik[kesadaran]</value>
      <webElementGuid>7177d475-b2e5-4f8e-8a26-41622ede093f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                                                                        COMPOS MENTIS
                                                                                                                    SOMNOLEN
                                                                                                                    SOPOR
                                                                                                                    COMA
                                                                                                                                                            </value>
      <webElementGuid>9cac75c2-fe22-42af-a45a-a6979327b0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box box-bordered&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/select[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>da79aad9-a1af-455d-bd3e-af024dfd4eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='PeriksaFisik[kesadaran]']</value>
      <webElementGuid>5d9be34a-3d64-46a7-b976-64758e117e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>2b227de6-6fcd-43d6-b6b8-076131f36344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>2884d573-d0a5-4d84-b593-269bd9e691bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>35efc06b-b025-4d7c-9346-1845bc012ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>05d8dc26-7fa5-492e-befa-46c91cc6b591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PeriksaFisik[kesadaran]' and (text() = '
                                                                                                                                                                        COMPOS MENTIS
                                                                                                                    SOMNOLEN
                                                                                                                    SOPOR
                                                                                                                    COMA
                                                                                                                                                            ' or . = '
                                                                                                                                                                        COMPOS MENTIS
                                                                                                                    SOMNOLEN
                                                                                                                    SOPOR
                                                                                                                    COMA
                                                                                                                                                            ')]</value>
      <webElementGuid>a070dcfc-a160-4b6f-b597-e351bebb9b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
