<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Anamnesaedukasi</name>
   <tag></tag>
   <elementGuidId>e56dbfe4-3c80-4beb-97dd-ed4d008f2848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='text_edukasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text_edukasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>09220b06-c61c-4a06-8895-7a4088212024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_edukasi</value>
      <webElementGuid>4b8df303-ef0d-44d3-ae27-eab521c02356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>5fc4e00a-48ac-4409-adb9-b5d0b1fc0687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>27f506e0-cd2b-41c0-8f49-9b322f1b9368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Anamnesa[edukasi]</value>
      <webElementGuid>62213390-6606-4f04-a0a4-2f3d50bf7daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>13c4ed20-705d-4106-bea7-892057df2af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Edukasi</value>
      <webElementGuid>1cfb7f4d-c3e7-410f-96bb-920fde655b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_edukasi&quot;)</value>
      <webElementGuid>8962786f-c474-4d70-98f1-788b7b17c100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='text_edukasi']</value>
      <webElementGuid>2bebef65-f1d0-4fab-848e-ba2f685f2eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[5]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>a8239611-c424-43e9-a68a-4020828e1dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>64f56f49-47a3-45ad-9d58-b4128a0f474d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'text_edukasi' and @name = 'Anamnesa[edukasi]' and @placeholder = 'Edukasi']</value>
      <webElementGuid>59b1096f-cc9c-47b4-b8ed-bb32e114cbfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
