<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Anamnesakeluhan_utama</name>
   <tag></tag>
   <elementGuidId>6c25f33b-6c28-4f37-a930-6c8eee8a61bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Anamnesa[keluhan_utama]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Anamnesa[keluhan_utama]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ff55e0a-cf05-4398-8042-e221199190c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ui-autocomplete-input</value>
      <webElementGuid>0939db76-1928-4d95-88ce-ec2948712179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a9356fae-1fbc-4cd2-b80a-22fa4968d48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Anamnesa[keluhan_utama]</value>
      <webElementGuid>b8187c0e-5857-4ca2-9464-84a118e6d73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>204cd7a9-9fd5-4202-926c-38a19a6d869a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Keluhan Utama *pisahkan dengan tanda koma ','</value>
      <webElementGuid>d3253a88-b5f5-4f34-b088-29403ba56233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f7304f3-2a3a-497d-adbe-bc760358f0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;form-group col-sm-6&quot;]/div[@class=&quot;col-sm-8 has-success&quot;]/textarea[@class=&quot;form-control input-sm ui-autocomplete-input&quot;]</value>
      <webElementGuid>475fef0b-baa3-4f52-b4a2-043fcc92e229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Anamnesa[keluhan_utama]']</value>
      <webElementGuid>59138659-547a-41ca-abd1-bdc1503ffdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div/div/div[2]/div[3]/div/textarea</value>
      <webElementGuid>bc31af15-5dcb-42ac-a37b-88ac1e3aa377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1adbbde1-74ec-4b69-baa5-55f815915f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Anamnesa[keluhan_utama]' and @placeholder = concat(&quot;🔍 Keluhan Utama *pisahkan dengan tanda koma &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot;)]</value>
      <webElementGuid>05fad0a5-0476-4fdc-92f4-d61d87486a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
