<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Anamnesaaskep</name>
   <tag></tag>
   <elementGuidId>8f9599f8-bde1-4edd-979b-1f9da973fe69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='text_riwayat'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.askep-text > div.col-sm-9.has-success > #text_riwayat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>84542bd8-7ef7-41e7-a7d4-7f13bb740bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_riwayat</value>
      <webElementGuid>c7f30fee-fe5a-4692-b646-a8ef8099e7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>9d3f5471-45b2-48b8-a296-0a0a6d46f2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>97acae2f-9a1e-4f39-bfdc-24a1c8386f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Anamnesa[askep]</value>
      <webElementGuid>1d03d205-05e8-4c24-ae1c-c2352028f9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>60a248db-20b4-4cb2-b3a4-4f87594bfa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asuhan Keperawatan</value>
      <webElementGuid>1140369d-ba60-4c73-946b-cfede8c39179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;box box-bordered&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;form-group askep-text&quot;]/div[@class=&quot;col-sm-9 has-success&quot;]/textarea[@id=&quot;text_riwayat&quot;]</value>
      <webElementGuid>d602b1e0-10e4-4ecc-b028-2200c4674a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='text_riwayat'])[2]</value>
      <webElementGuid>66547082-0d38-4ad0-886a-2bd4e7190f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div[5]/div/div[2]/div/div[5]/div/textarea</value>
      <webElementGuid>22895cd3-516c-48a5-954e-ccfc7e78da78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div[5]/div/textarea</value>
      <webElementGuid>058d8dae-e251-4ce0-9680-201376ffc09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'text_riwayat' and @name = 'Anamnesa[askep]' and @placeholder = 'Asuhan Keperawatan']</value>
      <webElementGuid>d55c1b0c-2507-4c13-bd73-4209003b680a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
