<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medis</name>
   <tag></tag>
   <elementGuidId>e1e0ed21-e7a8-48d5-9a09-5ae5d26646f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pelayanan_medis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_pelayanan_medis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4415cfb-963c-41b7-94cd-4df9e542bce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pelayanan_medis</value>
      <webElementGuid>e33aaa8b-8152-44dc-958c-c451f4074334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pelayanan?broadcastNotif=1</value>
      <webElementGuid>fa0aa663-5abc-4eaf-ac4f-27888774c3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medis</value>
      <webElementGuid>553da340-e0e8-463b-9c89-d53ef556671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pelayanan_medis&quot;)</value>
      <webElementGuid>68b5bdcb-1d1e-4f26-80b2-8fd95545fe89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pelayanan_medis']</value>
      <webElementGuid>498dfe11-5118-4f51-ac23-4f60d4b0a995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>e6de70ef-61ed-4242-accc-b8487e4a37f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Medis')])[2]</value>
      <webElementGuid>0e6b6599-085e-4068-8a84-edc9c735b4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelayanan'])[2]/following::a[1]</value>
      <webElementGuid>fc2045f7-5253-46db-8f6d-9d7bf5008e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panggil Antrean'])[1]/following::a[2]</value>
      <webElementGuid>5e933151-7b08-4da7-bbf9-26cb59a9c9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[1]/preceding::a[1]</value>
      <webElementGuid>a9707a8e-59c5-45ac-b027-33379ba0602c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obat Pasien'])[1]/preceding::a[2]</value>
      <webElementGuid>0c4b4fe0-735a-4b80-b98c-6a543d4b65f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medis']/parent::*</value>
      <webElementGuid>c07dfc33-5189-4a3b-b51e-c21a385b0e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pelayanan?broadcastNotif=1')]</value>
      <webElementGuid>76dc493c-e5b3-4b93-b8d4-68950c011cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>4177a064-b530-4992-8e80-1487d7616335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_pelayanan_medis' and @href = 'https://demo.epuskesmas.id/pelayanan?broadcastNotif=1' and (text() = 'Medis' or . = 'Medis')]</value>
      <webElementGuid>79d475ad-79d1-431c-b103-b3fedb99c048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
