<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pasien  KK</name>
   <tag></tag>
   <elementGuidId>a01a7bc0-2672-46a3-96c7-9a87e07d676b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pendaftaran_pasien']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_pendaftaran_pasien</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac296de6-8ca6-4451-b6b1-f14a09508f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pendaftaran_pasien</value>
      <webElementGuid>214e204e-0d20-4495-9cc7-d276f035614c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pasien?broadcastNotif=1</value>
      <webElementGuid>d76203d1-01a9-42e3-9951-a38ca080da87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pasien &amp; KK</value>
      <webElementGuid>320744e9-d78f-4c29-90d2-0dc96f2b6905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pendaftaran_pasien&quot;)</value>
      <webElementGuid>8195a21d-8893-46b1-a3f1-339387a81b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pendaftaran_pasien']</value>
      <webElementGuid>8d15d833-5c94-48e6-92a3-107f1cf1f9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul/li/ul/li/a</value>
      <webElementGuid>d3832967-4ceb-4a4c-aef9-03abb10d7bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pasien &amp; KK')]</value>
      <webElementGuid>a3f21519-1f6f-447f-a8c6-18c0aa141d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>c862a0d1-5dbe-4545-98b4-1cc56b3c9e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran Pasien'])[1]/preceding::a[1]</value>
      <webElementGuid>064cdfa4-a890-42a7-8dba-83f2791584d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::a[2]</value>
      <webElementGuid>c80ec811-bd6a-4c98-9a5e-c195a5c68e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pasien &amp; KK']/parent::*</value>
      <webElementGuid>6d6a90a6-a704-41ec-840a-289a7d3ff636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pasien?broadcastNotif=1')]</value>
      <webElementGuid>6896c736-f0db-4f62-bd3c-3fe596cd62dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>c191f15e-1805-4291-87ed-e73a05ff1862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_pendaftaran_pasien' and @href = 'https://demo.epuskesmas.id/pasien?broadcastNotif=1' and (text() = 'Pasien &amp; KK' or . = 'Pasien &amp; KK')]</value>
      <webElementGuid>724fed87-b7cf-4d71-b335-5738cdb7e40f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
