<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keluar</name>
   <tag></tag>
   <elementGuidId>1c161b25-a72c-4b09-9028-a03080ef2a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_user_logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_user_logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5241989-30fa-4554-9576-f283b917a172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_user_logout</value>
      <webElementGuid>07469ba2-4878-43a7-8f75-3123bd031b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/logout</value>
      <webElementGuid>418bac79-25a1-40d8-a6ed-c58cd14341a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault();
                                                     document.getElementById('logout-form').submit();</value>
      <webElementGuid>9b8a83ce-1d67-4492-945e-9236d912a7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Keluar
                                        </value>
      <webElementGuid>691bc907-0d58-444d-b9af-530cf0fa67b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_user_logout&quot;)</value>
      <webElementGuid>23470510-7a6b-41b6-8660-656091f4cd94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_user_logout']</value>
      <webElementGuid>6ba851f1-3290-48ac-81c1-01c5b4725bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul[2]/li[3]/ul/li[6]/a</value>
      <webElementGuid>a15bc9b0-85d5-407d-aa37-d3cc065c451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>1e562467-ef88-414a-b525-2311ea9d29ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umpan Balik'])[1]/following::a[2]</value>
      <webElementGuid>7f5c55b3-8255-4383-bafd-b6b2d6c94ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/following::a[4]</value>
      <webElementGuid>d380922a-55b5-4108-8eb2-e72f3b621786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pasien dan Kartu Keluarga'])[1]/preceding::a[1]</value>
      <webElementGuid>540e08f9-430a-4d1f-9ff1-c36490864c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur Tunda'])[1]/preceding::a[1]</value>
      <webElementGuid>b270419c-6b7f-4e2b-9ace-f715edace65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>de497eca-eb46-4bbd-8606-20bbac1d64c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/logout')]</value>
      <webElementGuid>dcaf5ed9-7140-464b-a648-f93128d43c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/ul/li[6]/a</value>
      <webElementGuid>9cd1f2a3-a7a4-4d8a-adcd-c13fd4c722b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_user_logout' and @href = 'https://demo.epuskesmas.id/logout' and (text() = '
                                            Keluar
                                        ' or . = '
                                            Keluar
                                        ')]</value>
      <webElementGuid>136db262-eb67-4f8d-a4b4-2b65b2c3c83b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
