<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>6f65579d-d14d-40ef-bd26-0a2e55b6123f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07fa7882-9b90-473a-a0ca-0ac4a0bcc42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_delete</value>
      <webElementGuid>5c2e9fa7-8f37-4671-a7f3-a524ac101788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e532b79-133d-4db3-8fdd-1cc0378be7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger</value>
      <webElementGuid>d76654ef-43aa-458e-9419-7bbc871417d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteChecked(this);</value>
      <webElementGuid>c42105b6-3866-4d12-ac6f-9cee8f30ea61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>b7d4459f-270d-4893-a05e-8acdcf39f439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_delete&quot;)</value>
      <webElementGuid>1c391e0e-4acf-46de-b615-ae3395f5c95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_delete']</value>
      <webElementGuid>945c616a-ad24-4519-abbb-f7ca875be973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='button-wrapper-general']/button</value>
      <webElementGuid>29eafa40-8be8-4ab2-ab08-592294f5958a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembalikan'])[1]/following::button[1]</value>
      <webElementGuid>ac0b83c9-885f-4d04-8908-40b6e79bf90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Permanen'])[1]/following::button[2]</value>
      <webElementGuid>ea821796-51ce-4fe1-8c54-2d819c646787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/preceding::button[1]</value>
      <webElementGuid>477b87e6-2e94-408e-96cc-ba7238e5f416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::button[1]</value>
      <webElementGuid>3db162ed-c4af-46c2-87c9-843bc8dbdafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus']/parent::*</value>
      <webElementGuid>142eeb3e-91de-4c31-8891-920fd5379616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8fc467de-7052-457d-a1ee-948e00e5a778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_delete' and @type = 'button' and (text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>820d0712-752b-4544-82b1-7fb4ff29a3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
