<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keluar</name>
   <tag></tag>
   <elementGuidId>e4903572-6866-46a2-bc8a-b6949917991b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_user_logout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_user_logout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd9d7cae-1258-47ae-ab1b-9a9821220789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_user_logout</value>
      <webElementGuid>1d90ae44-e0c1-48a3-a2a7-7f6377aaed20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/logout</value>
      <webElementGuid>7ff423a2-d18f-4704-8632-d36de6a8e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault();
                                                     document.getElementById('logout-form').submit();</value>
      <webElementGuid>2e410fd8-9319-4dd4-82a2-d68e70953132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Keluar
                                        </value>
      <webElementGuid>cbab5b0a-90d9-4c34-8bec-148c08df7ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_user_logout&quot;)</value>
      <webElementGuid>cce694f3-0f37-478d-b918-4ab3b3031ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_user_logout']</value>
      <webElementGuid>8c619698-705a-4220-a327-69e2112f1104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul[2]/li[3]/ul/li[6]/a</value>
      <webElementGuid>d703a3da-7c00-403d-bcbb-2ffc1ca89831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>cb422f53-0e57-4e83-8e01-994a9a35ee1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umpan Balik'])[1]/following::a[2]</value>
      <webElementGuid>b35fb2aa-761b-45f7-bbdf-791bf4cbc086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/following::a[4]</value>
      <webElementGuid>7c8f809e-f4cd-47e8-8322-98736bb6389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Baru Resep'])[1]/preceding::a[1]</value>
      <webElementGuid>63530c16-b560-4d58-a266-897c4bf64d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/preceding::a[1]</value>
      <webElementGuid>20039124-97b1-4c75-9ced-e2dfdbd14268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>4f8c052e-48fa-4f50-9b7e-7bb06fc3186c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/logout')]</value>
      <webElementGuid>666a10bc-d4af-46a5-8b2e-4f0de60d51f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/ul/li[6]/a</value>
      <webElementGuid>f7969cd9-df63-4961-a123-1cd470da10ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_user_logout' and @href = 'https://demo.epuskesmas.id/logout' and (text() = '
                                            Keluar
                                        ' or . = '
                                            Keluar
                                        ')]</value>
      <webElementGuid>a2ce499c-19ae-4500-bdd6-8c76f909c627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
