<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_01006 - Amoksilin kaplet 500 mg (1205)</name>
   <tag></tag>
   <elementGuidId>d7c345a2-215d-4ed2-817f-54d0c67ed307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9588e21-18dd-4426-b8d0-cc0f959007cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-28</value>
      <webElementGuid>915c2a08-b2db-4a93-9204-0b60a99a4769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e49059ec-30cf-447d-8394-ab36c1443bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>84b55853-82a2-4431-bc58-365ed112479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01006 - Amoksilin kaplet 500 mg (1205)</value>
      <webElementGuid>9a6a1f2b-0aa9-400a-aa8a-8b3fea2422fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-28&quot;)</value>
      <webElementGuid>7855579a-6cf6-4027-879a-a0c51f5dc5ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-28']</value>
      <webElementGuid>0d049f81-f710-466c-b9a7-a5dc2b574380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-6']/li[2]/div</value>
      <webElementGuid>8a6f0fd4-94d4-461b-adc7-ddb1bec7ed45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifikasi'])[1]/following::div[6]</value>
      <webElementGuid>40aa36b0-1742-4761-93d1-c9767f0e5318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memuat...'])[3]/following::div[13]</value>
      <webElementGuid>1493a91a-2377-4b43-a7f8-70e67307b817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No search results.'])[1]/preceding::div[2]</value>
      <webElementGuid>7d0a27c9-41e9-43d1-b43e-1ca64c3df4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amoksilin kaplet 500 mg'])[1]/preceding::div[4]</value>
      <webElementGuid>6ee68af4-8575-4df8-9dcc-2478720986b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01006 - Amoksilin kaplet 500 mg (1205)']/parent::*</value>
      <webElementGuid>73397953-226e-4deb-ac91-af3c5f200f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li[2]/div</value>
      <webElementGuid>881f0798-4e9c-476c-91fd-4b5cb41fbfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-28' and (text() = '01006 - Amoksilin kaplet 500 mg (1205)' or . = '01006 - Amoksilin kaplet 500 mg (1205)')]</value>
      <webElementGuid>b14f7d88-8956-4b6a-8b52-e209d2e400e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
