<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yandri (Staf Non Medis)</name>
   <tag></tag>
   <elementGuidId>cefafbdd-8608-411d-a5e6-9aba98739488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2722e345-d974-41dc-809a-0216ed48bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-8</value>
      <webElementGuid>d8f0544d-f75d-437e-b771-c2ab29b77ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>884b1570-f1ac-46e2-b591-af6cecd0fb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>ab54cfc4-94fa-489c-ad82-a8eb6290f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yandri (Staf Non Medis)</value>
      <webElementGuid>18f27512-9752-4eac-8e16-f1f37b4e112d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-8&quot;)</value>
      <webElementGuid>65fb32df-7b69-4d5c-b5a6-50893028fbbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-8']</value>
      <webElementGuid>69541a83-8423-4aa4-9df0-1215c8d01a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[2]/div</value>
      <webElementGuid>588382cf-a90d-43b7-a191-8d337d041bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ray S.Farm (Apoteker)'])[1]/following::div[1]</value>
      <webElementGuid>8a87f38c-7ac5-47ed-a798-a4508211ba15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Roll'])[1]/following::div[2]</value>
      <webElementGuid>ee779209-fdf2-4cda-9289-d674b8adb957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR. YUDISTIRA (Dokter Gigi)'])[1]/preceding::div[1]</value>
      <webElementGuid>3aa503f8-abb9-43ab-a870-7fcb83ea164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR.HILMAI PICAL MUSLIM (Dokter Umum)'])[1]/preceding::div[2]</value>
      <webElementGuid>922902f9-6301-46bb-924f-f146536c08b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yandri (Staf Non Medis)']/parent::*</value>
      <webElementGuid>b9e40d33-36d6-4fbd-a5a3-312cbf5e164f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>1fa90dff-b1f3-42ba-8404-83635656d1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-8' and (text() = 'Yandri (Staf Non Medis)' or . = 'Yandri (Staf Non Medis)')]</value>
      <webElementGuid>e576e170-fbff-4da7-b387-3ef1e1ce3896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
