<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DR RAFLES (Dokter Umum)</name>
   <tag></tag>
   <elementGuidId>c5dce266-2c17-4e7d-9506-457a75286d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb42c8d4-fcee-45ef-81b3-7fb40fdc1d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-21</value>
      <webElementGuid>f39f89d1-a777-4142-aa63-9455610f0fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cf0bbf2c-3e0d-4ce2-a5c0-e34f9e4c7343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>d7ce084f-385a-4559-97d8-4b11d75d1a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DR RAFLES (Dokter Umum)</value>
      <webElementGuid>b8c8dd51-15ad-45a8-9e90-99245c565597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-21&quot;)</value>
      <webElementGuid>255c7e7e-33c6-4c01-a268-2664681fbd3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-21']</value>
      <webElementGuid>34cbbc83-ea46-48ed-ab91-3afa661a8d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-3']/li[5]/div</value>
      <webElementGuid>e8a83cdb-725b-4173-ae5a-d1adba3f8429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR.HILMAI PICAL MUSLIM (Dokter Umum)'])[2]/following::div[1]</value>
      <webElementGuid>e2bfadf2-9242-4b38-9f82-b9395066703c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR. YUDISTIRA (Dokter Gigi)'])[2]/following::div[2]</value>
      <webElementGuid>5c59b443-4e4a-4c99-9279-4f2d3a3c8f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dr.Rizki Amalia (Dokter Umum)'])[2]/preceding::div[1]</value>
      <webElementGuid>5cb43ef3-5534-445b-bf1d-83a9a4c4153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sri Sudartik,SST (Bidan)'])[2]/preceding::div[2]</value>
      <webElementGuid>656df16f-7406-4a63-9248-e1f61e7f3b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li[5]/div</value>
      <webElementGuid>ba1c3144-aab8-4210-925b-c06a144918ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-21' and (text() = 'DR RAFLES (Dokter Umum)' or . = 'DR RAFLES (Dokter Umum)')]</value>
      <webElementGuid>ba8592af-e553-48e1-8bdd-75d6b27ba3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
