<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1X1 TETES</name>
   <tag></tag>
   <elementGuidId>16f4159a-c522-4a78-94e5-c9e499f86506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-32']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-32</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a12222a-2e68-401a-a754-c5e6702a67a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-32</value>
      <webElementGuid>06f661a2-dc58-4267-81e9-cee7c695eab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6f3f0907-60b9-4d7b-9acf-2b343d89f37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>cac29251-fd65-4919-a134-25f8e2d10d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1X1 TETES</value>
      <webElementGuid>ec5c9db4-0433-4236-95ce-b4d722164b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-32&quot;)</value>
      <webElementGuid>2dd8187e-d2b1-4c92-be81-34fcd5dc31c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-32']</value>
      <webElementGuid>f117acac-cffa-491e-9529-3115c9c6c5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-5']/li[3]/div</value>
      <webElementGuid>e105a4b1-00d1-47e8-9cf4-8f4f584fcd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/following::div[2]</value>
      <webElementGuid>3bf4cfba-aa32-4c12-8cbd-5f683c4643ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DR RAFLES'])[2]/following::div[4]</value>
      <webElementGuid>4eb2b607-806d-4acd-bd1e-49f4d01eea00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[2]/preceding::div[4]</value>
      <webElementGuid>c8d8e028-ac0d-4b71-82a9-66bbad8dbb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memuat...'])[1]/preceding::div[8]</value>
      <webElementGuid>09dfd69e-316a-4be4-a88e-9a3a10801cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1X1 TETES']/parent::*</value>
      <webElementGuid>70564041-7173-4e0f-8277-8d115a0ec567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[5]/li[3]/div</value>
      <webElementGuid>f84e3d0f-a2d9-4128-8c58-ad4547c964a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-32' and (text() = '1X1 TETES' or . = '1X1 TETES')]</value>
      <webElementGuid>7d3bbe6e-b0c9-4a8a-a43c-afbe89e291d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
