<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_obat_nama</name>
   <tag></tag>
   <elementGuidId>95872be7-9598-467b-8e8a-ff1c8b671e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='obat_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;obat_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17d7269f-e59e-482b-a36d-4c2d8d71e913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab8144b9-c440-47b2-8009-fdfe54fa4497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ui-autocomplete-input</value>
      <webElementGuid>0920e535-d5ac-4a60-a53b-10d8c52983b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>obat_nama</value>
      <webElementGuid>03a10702-2bc1-478f-8a0c-7dab0d715de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>obat_nama</value>
      <webElementGuid>016f6342-3aab-41cf-a1df-bcac1b27f2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Obat</value>
      <webElementGuid>72dc61ef-15ac-4ddf-a482-4fb27065c6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>c6f08ed1-b238-4c7f-974c-41b820eea47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>228b95d0-20e2-4292-8bab-3fafa1ad7d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_1&quot;)/td[3]/input[@class=&quot;form-control input-sm ui-autocomplete-input&quot;]</value>
      <webElementGuid>3b10806a-df1a-470c-9987-e4ccdb2cc4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='obat_nama']</value>
      <webElementGuid>851935a8-50d3-44da-a9e4-2b742d965d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[3]/input[5]</value>
      <webElementGuid>086100ec-20e2-41a2-9ad3-da3d3f81e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>c1d71a66-aa60-4d6e-b988-addf7d9297a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'obat_nama' and @placeholder = '🔍 Nama Obat']</value>
      <webElementGuid>2a2ad76d-9bec-4246-9f61-1217307d2665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
