<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_ResepDetail1obat_keterangan</name>
   <tag></tag>
   <elementGuidId>5b5da452-baee-4264-bf8c-38c97e0cf63d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ResepDetail[1][obat_keterangan]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ResepDetail[1][obat_keterangan]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1b1c36c-6a00-4c52-b2ee-03e99db4ef01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b82bbf35-f4e3-475a-8c24-c8c593d432f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>3b8f7fdd-348e-4c09-8f55-ec61c8e84905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>obat_keterangan</value>
      <webElementGuid>f1f8622e-9aff-404c-9eaa-6b8490158b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ResepDetail[1][obat_keterangan]</value>
      <webElementGuid>7d777211-0ade-4dfa-8294-f46b33de94ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>05f8f65e-7d0f-435e-a970-2be3f1f8cff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>d0017e57-e71f-4a59-ae0a-a4462e09b54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_1&quot;)/td[7]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>9d26829d-e820-4854-9bac-6c07d27e2beb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ResepDetail[1][obat_keterangan]']</value>
      <webElementGuid>0a66ddb3-5676-4c78-b6cb-d7c837a2312a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[7]/input</value>
      <webElementGuid>f25e0035-90ee-442e-96b7-5cdcf3404582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>4a60a3bb-c3c0-4376-b941-4f7fb155c228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ResepDetail[1][obat_keterangan]' and @placeholder = 'Keterangan']</value>
      <webElementGuid>10a90a38-c2ec-456b-88c4-8431b5f59d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
