<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_ResepDetail1obat_jumlah_pe_125b89</name>
   <tag></tag>
   <elementGuidId>5e0a5375-bbad-453e-a290-7b978aa54221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ResepDetail[1][obat_jumlah_permintaan]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ResepDetail[1][obat_jumlah_permintaan]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>115ed6fa-f3b7-439c-b7d6-0429145d26ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f3d6ac84-cce8-453f-88ad-002883806c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2ff3e08d-6cea-469d-ae06-941208d2c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a79e85ad-f69f-4498-8a31-255db39a2854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>c8d307c0-2beb-49dc-ab46-d8a37139c698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>obat_jumlah_permintaan</value>
      <webElementGuid>e0a3418f-b74c-4c59-822c-6c87756dc727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ResepDetail[1][obat_jumlah_permintaan]</value>
      <webElementGuid>0cd39c08-fe39-4767-96c0-9e8385bc35b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>d444141a-0986-474f-86ea-638307d32776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>b8f8df9f-50ab-40a1-9399-d2e61d4dc7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_1&quot;)/td[2]/input[@class=&quot;form-control input-sm&quot;]</value>
      <webElementGuid>74e37c38-8683-44e8-bd38-6e96359cf536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ResepDetail[1][obat_jumlah_permintaan]']</value>
      <webElementGuid>17e680a3-701e-4976-9eb4-2def31cbc799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[2]/input</value>
      <webElementGuid>68cdae59-de29-49bc-89ce-9de79875ac02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e032cd5e-f1e8-4a3f-9cc5-390e27c3a296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'ResepDetail[1][obat_jumlah_permintaan]' and @placeholder = 'Qty']</value>
      <webElementGuid>2fd028cc-5448-4f16-81a4-633b376d9929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
