<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_signa_nama</name>
   <tag></tag>
   <elementGuidId>7b924908-b8e6-4cfa-ab7c-c80de96697b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='signa_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;signa_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1f119ea-fc0e-4f4a-9dc6-5e6e90d78b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d94aa5d-39f6-43ec-8322-cda7e1e0d861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ui-autocomplete-input</value>
      <webElementGuid>5eff26d3-44f9-4daf-97b0-ea76750f2894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>signa_nama</value>
      <webElementGuid>a7bfad5e-8b41-44b0-99b3-f8948273cd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signa_nama</value>
      <webElementGuid>13ddf05b-1f53-4730-ab8f-1cb0b738d217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Cari Resep Signa</value>
      <webElementGuid>f6b57594-fb64-4826-a656-fc48c8c3fe35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>df76fd20-47ee-4fc3-aaff-fcee0b07e459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8a1e2a5-7798-4a57-a870-5e42a9791300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_1&quot;)/td[5]/input[@class=&quot;form-control input-sm ui-autocomplete-input&quot;]</value>
      <webElementGuid>bd32e2a8-75ce-474d-89d8-45d2b22cb0ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='signa_nama']</value>
      <webElementGuid>428a525b-f0bb-47f0-b6be-d5524b70ec49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_1']/td[5]/input[2]</value>
      <webElementGuid>41f086bf-9b30-41bd-a696-071f4f0a7855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input[2]</value>
      <webElementGuid>8b297872-76c9-46e1-b78c-b2c5b70d005a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'signa_nama' and @placeholder = '🔍 Cari Resep Signa']</value>
      <webElementGuid>6c5f67a8-58a0-47a1-99c5-844b83d014d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
