<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perawat  Bidan  Nutrisionist  Sanitar_eb3618</name>
   <tag></tag>
   <elementGuidId>c695928d-096b-4e9b-9889-0f8c07f62cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='perawat_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;perawat_nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f31096a0-9e5b-4c0e-a15e-6defa134781b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f3b2535-80e5-43f3-a68e-845461bb4113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm ui-autocomplete-input</value>
      <webElementGuid>8e08159a-bb40-4505-b0d7-07323a316e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>perawat_nama</value>
      <webElementGuid>2258c74c-d1a3-4639-8ed1-eb0d28f100ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>🔍 Nama Asisten Dokter / Bidan / Perawat</value>
      <webElementGuid>56c550d7-0ba4-4153-b91d-7a91b379d2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>177882f5-d4c4-4d6d-a94c-a80dda06c518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a47fc349-7a1d-4de9-9b57-fa94a749e187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_create&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;panel-body box-bordered&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-8 has-success&quot;]/input[@class=&quot;form-control input-sm ui-autocomplete-input&quot;]</value>
      <webElementGuid>0d291221-42ab-4523-aa2d-b736fe6d1abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='perawat_nama']</value>
      <webElementGuid>50fa52c5-0dbb-4234-914b-9215e666ed2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_create']/div/div[2]/div[4]/div/input[2]</value>
      <webElementGuid>a75e9920-4f93-4cbc-94dd-6af661a7b581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input[2]</value>
      <webElementGuid>a9fa804c-893d-4f8a-a3ee-e777610cafcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'perawat_nama' and @placeholder = '🔍 Nama Asisten Dokter / Bidan / Perawat']</value>
      <webElementGuid>ebea8617-95e4-4cae-bae2-b302dc1d2aa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
