<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ePuskesmas</name>
   <tag></tag>
   <elementGuidId>613d8f18-6103-453a-b209-854967b57753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c418c901-f3cc-4eab-937f-9eae0e82925b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ePuskesmas</value>
      <webElementGuid>bfd8f511-305f-4010-a99a-0be7d4a1118b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/nav[@class=&quot;navbar-inner fixed-bottom navbar-light&quot;]/ul[@class=&quot;col-md-4 col-sm-4 col-xs-4 bg-primary-2 green&quot;]/li[1]/ul[@class=&quot;drop-menu menu-4&quot;]/li[@class=&quot;green&quot;]/a[1]/span[1]</value>
      <webElementGuid>f2159705-a484-4140-8ec9-68454a6f22d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      <webElementGuid>be10c5fc-40b1-4761-854a-74cbefe2096e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puskesmas . Dinas Kesehatan'])[1]/following::span[1]</value>
      <webElementGuid>6c601b3c-953e-4035-8902-ab7eb8cc6d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ePosyandu'])[1]/preceding::span[1]</value>
      <webElementGuid>8ea3fdd8-3bd7-4320-b143-0be35f6e917b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eClinic'])[1]/preceding::span[2]</value>
      <webElementGuid>93a8a22d-c382-42ef-92b5-e99725194c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>23ab2e8f-f032-4fbb-a1bc-02f821325543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ePuskesmas' or . = 'ePuskesmas')]</value>
      <webElementGuid>72ed63b4-2c51-4eac-879c-e2368bf292a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
