<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ePuskesmas</name>
   <tag></tag>
   <elementGuidId>a9f4678a-a0ff-4b1c-9edb-0a57b5225342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b32f27bd-c1fc-4bbf-93ba-a52b93d2a3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ePuskesmas</value>
      <webElementGuid>c64056fd-ad04-43f0-bc0b-21c300dc8a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/nav[@class=&quot;navbar-inner fixed-bottom navbar-light&quot;]/ul[@class=&quot;col-md-4 col-sm-4 col-xs-4 bg-primary-2 green&quot;]/li[1]/ul[@class=&quot;drop-menu menu-4&quot;]/li[@class=&quot;green&quot;]/a[1]/span[1]</value>
      <webElementGuid>c03ceb17-0ed6-431d-9372-7b80552e47b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/div/div/div/nav/ul/li/ul/li/a/span</value>
      <webElementGuid>b75b3da4-e374-4305-b8c6-dbe14ae4be13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puskesmas . Dinas Kesehatan'])[1]/following::span[1]</value>
      <webElementGuid>e7f20a86-047f-41f0-bad1-5df8475224d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ePosyandu'])[1]/preceding::span[1]</value>
      <webElementGuid>046c198f-c213-408a-8f41-2d33baf01ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eClinic'])[1]/preceding::span[2]</value>
      <webElementGuid>756427c4-d159-4d34-8086-5639782a4257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>0abd8105-dea2-40e4-ac73-8588716de0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ePuskesmas' or . = 'ePuskesmas')]</value>
      <webElementGuid>316642d8-b8f5-4956-8273-69f2749c75a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
