<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_BUDIII</name>
   <tag></tag>
   <elementGuidId>b1e9e9e9-1f4b-420c-8fb8-62d67fc9f3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datatableWrapper']/div[2]/table/tbody/tr[7]/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2fb00d95-2fd2-4206-807b-42601a35dd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUDIII</value>
      <webElementGuid>073ef7cd-9e1b-4bac-b2f3-cbd0bcf6e36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatableWrapper&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-hover table-condensed table-sortable datatable&quot;]/tbody[1]/tr[7]/td[5]</value>
      <webElementGuid>d7dcdea8-ced4-4ec9-a991-6c3217b2ded3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatableWrapper']/div[2]/table/tbody/tr[7]/td[5]</value>
      <webElementGuid>f0801e25-bebf-4444-86fc-93528823200c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label 2'])[6]/following::td[6]</value>
      <webElementGuid>1b348a8d-e706-4bb0-add5-9246bccf91f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropup'])[6]/following::td[6]</value>
      <webElementGuid>ad45c3ea-1be0-4901-b5a9-2ff3db90116e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laki-laki'])[7]/preceding::td[3]</value>
      <webElementGuid>cbb912c7-7eb4-426b-9aa7-0135137ddaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDAN, 19-September-1989'])[1]/preceding::td[4]</value>
      <webElementGuid>3d8a4416-7a21-4982-a9aa-3d8dd9ef02dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUDIII']/parent::*</value>
      <webElementGuid>b4376d1e-4265-48ab-8103-e311c75c4fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]</value>
      <webElementGuid>1ca96025-1648-4a6b-9db4-de9222b2f266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BUDIII' or . = 'BUDIII')]</value>
      <webElementGuid>eb796f50-f862-4eac-9a97-853986ff2ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
