<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Semua</name>
   <tag></tag>
   <elementGuidId>cfbf7f30-8631-4513-a68a-1534a1beac99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_index']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_index</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff74ba20-8400-4323-bb35-e18da847d4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pasien</value>
      <webElementGuid>6fe9e087-e60d-43a8-9210-57a027f639f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_index</value>
      <webElementGuid>d1e93725-8b30-45b5-b1d4-ad8ebe6f61fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8072267f-66b9-4d5a-8d93-436adb27d6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>2c7579e4-8b96-47f9-a7ed-e481e531fdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Semua</value>
      <webElementGuid>c2da39cb-50d0-440c-99e6-3f4a842e58bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_index&quot;)</value>
      <webElementGuid>4faf2383-000d-4138-a61a-e617074d462c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_index']</value>
      <webElementGuid>f4cb732f-55e5-40a9-9f65-c266660acdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/span[2]/a[3]</value>
      <webElementGuid>61de1586-51f0-4efa-942e-541862eaf3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Semua')]</value>
      <webElementGuid>6e154c7d-f243-4a60-a205-8713244efac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Baru'])[1]/following::a[1]</value>
      <webElementGuid>544fbd1b-9c4c-4d0a-8bcb-16c9109e85f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koreksi Umur'])[1]/following::a[2]</value>
      <webElementGuid>06a9a853-0cb7-4d4b-a1a2-8b04cd4704ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[1]/preceding::a[1]</value>
      <webElementGuid>817089af-878f-4122-8743-16af8aecb504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran'])[2]/preceding::a[2]</value>
      <webElementGuid>26d6ccab-0aca-4879-abd0-c4e1e83e45b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Semua']/parent::*</value>
      <webElementGuid>e73cf041-883e-4e9e-bba0-027933d031ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demo.epuskesmas.id/pasien')])[4]</value>
      <webElementGuid>f868e278-c3f5-4bdb-91da-75774d370a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>cc6cfc09-979f-4994-9e39-8445cc1cdc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.epuskesmas.id/pasien' and @id = 'button_index' and @type = 'button' and (text() = 'Lihat Semua' or . = 'Lihat Semua')]</value>
      <webElementGuid>4400c10a-4637-42a6-a027-69f164158525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
