<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pasien  KK</name>
   <tag></tag>
   <elementGuidId>6d9ea94c-bc7d-44b3-a36c-20e4f22885e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_pendaftaran_pasien</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pendaftaran_pasien']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e3bc349-1631-4617-bc5b-7218ba9b5531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pendaftaran_pasien</value>
      <webElementGuid>12d990bf-80f4-4775-b1a9-1641641ec991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/pasien?broadcastNotif=1</value>
      <webElementGuid>4aea7795-dc7e-445a-b44c-89559ab319f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pasien &amp; KK</value>
      <webElementGuid>425a2309-54e2-4b1f-a0e8-f69af7dd515d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pendaftaran_pasien&quot;)</value>
      <webElementGuid>0b15ac87-bd61-493c-a574-3ac16aae7215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pendaftaran_pasien']</value>
      <webElementGuid>6f373f0c-3f94-4891-a139-678a26630de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/ul/li/ul/li/a</value>
      <webElementGuid>f6c3a3c7-1731-430c-a47e-794a51d4436f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pasien &amp; KK')]</value>
      <webElementGuid>43ba9d20-4c34-4c62-ad46-99e227450d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>b559bb48-cd62-47ac-8a40-d92a072bab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran Pasien'])[1]/preceding::a[1]</value>
      <webElementGuid>d3ff04b8-e991-40af-b1d2-e5eda4418823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::a[2]</value>
      <webElementGuid>551751de-2b6f-4b1d-abb1-3fe302505bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pasien &amp; KK']/parent::*</value>
      <webElementGuid>a9799df6-776d-458b-a137-1b85b236fac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.epuskesmas.id/pasien?broadcastNotif=1')]</value>
      <webElementGuid>a38a9f2a-02fd-489c-9802-41a249a3c8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>fb7431d5-d39e-4129-998d-71d6f75e02b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu_pendaftaran_pasien' and @href = 'https://demo.epuskesmas.id/pasien?broadcastNotif=1' and (text() = 'Pasien &amp; KK' or . = 'Pasien &amp; KK')]</value>
      <webElementGuid>9b5bd5e8-0337-4c0b-a4fc-2e7185965428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
