<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anamnesa</name>
   <tag></tag>
   <elementGuidId>d57b2979-d2ee-48c2-b7ad-7846807cfee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button_anamnesa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_anamnesa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>356f8c80-bd74-40b0-ba83-441374c6fd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.epuskesmas.id/anamnesa/create/9651?from='pelayanan'&amp;action='edit'</value>
      <webElementGuid>8eaaa547-d3e4-4cb7-a256-6f6fd5c471f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_anamnesa</value>
      <webElementGuid>81951bfa-a30d-4d4f-a507-45cf929bc99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-primary</value>
      <webElementGuid>51e47bd5-8f40-4b23-a9d8-d1440fb9ff43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anamnesa</value>
      <webElementGuid>33f5732f-83ff-47fa-a82a-61e21c7c3244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_anamnesa&quot;)</value>
      <webElementGuid>08b551eb-d806-4f45-8707-548a4c51547d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button_anamnesa']</value>
      <webElementGuid>604379eb-e745-4f85-a684-29dc2529dd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[2]/div/div/a[2]</value>
      <webElementGuid>3410494b-d3dc-4235-99c9-9352abd6378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anamnesa')]</value>
      <webElementGuid>7a9ecf9d-e11c-4a23-8927-10e457cf4f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Riwayat'])[1]/following::a[1]</value>
      <webElementGuid>5ffd8eb1-6298-49a4-8ac6-d9b3cbb683f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[2]/following::a[2]</value>
      <webElementGuid>f02067af-3e8e-4d0e-b806-bc252ace94c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosa'])[2]/preceding::a[1]</value>
      <webElementGuid>7d2a83a0-8c03-4e89-80b7-de4d64956139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resep'])[2]/preceding::a[2]</value>
      <webElementGuid>8a3f5467-2a4d-40b4-b0d4-b49ab3476c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anamnesa']/parent::*</value>
      <webElementGuid>c22b25d1-ca9b-48cc-a5f3-240d65e7480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;https://demo.epuskesmas.id/anamnesa/create/9651?from='pelayanan'&amp;action='edit'&quot;)]</value>
      <webElementGuid>2d61b5b4-7301-455f-935b-719a6e4995a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>1e7f0cc5-81d3-4d99-836c-0cbfa5d1d1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;https://demo.epuskesmas.id/anamnesa/create/9651?from=&quot; , &quot;'&quot; , &quot;pelayanan&quot; , &quot;'&quot; , &quot;&amp;action=&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot;) and @id = 'button_anamnesa' and (text() = 'Anamnesa' or . = 'Anamnesa')]</value>
      <webElementGuid>57c41fd2-64c8-4cf7-8649-d174f7e76725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
